// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

/**
 * Protobuf enum {@code skymouse.ButtonState}
 */
@com.google.protobuf.Generated
public enum ButtonState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>STATE_UNKNOWN = 0;</code>
   */
  STATE_UNKNOWN(0),
  /**
   * <code>STATE_DOWN = 1;</code>
   */
  STATE_DOWN(1),
  /**
   * <code>STATE_UP = 2;</code>
   */
  STATE_UP(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ButtonState");
  }
  /**
   * <code>STATE_UNKNOWN = 0;</code>
   */
  public static final int STATE_UNKNOWN_VALUE = 0;
  /**
   * <code>STATE_DOWN = 1;</code>
   */
  public static final int STATE_DOWN_VALUE = 1;
  /**
   * <code>STATE_UP = 2;</code>
   */
  public static final int STATE_UP_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ButtonState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ButtonState forNumber(int value) {
    switch (value) {
      case 0: return STATE_UNKNOWN;
      case 1: return STATE_DOWN;
      case 2: return STATE_UP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ButtonState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ButtonState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ButtonState>() {
          public ButtonState findValueByNumber(int number) {
            return ButtonState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.skymouse.skymouseclient.proto.Skymouse.getDescriptor().getEnumType(1);
  }

  private static final ButtonState[] VALUES = values();

  public static ButtonState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ButtonState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:skymouse.ButtonState)
}

