// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

/**
 * Protobuf type {@code skymouse.ClickEvent}
 */
@com.google.protobuf.Generated
public final class ClickEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:skymouse.ClickEvent)
    ClickEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ClickEvent");
  }
  // Use ClickEvent.newBuilder() to construct.
  private ClickEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ClickEvent() {
    button_ = 0;
    state_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_ClickEvent_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_ClickEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_ClickEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.skymouse.skymouseclient.proto.ClickEvent.class, com.skymouse.skymouseclient.proto.ClickEvent.Builder.class);
  }

  public static final int BUTTON_FIELD_NUMBER = 1;
  private int button_ = 0;
  /**
   * <code>.skymouse.MouseButton button = 1;</code>
   * @return The enum numeric value on the wire for button.
   */
  @java.lang.Override public int getButtonValue() {
    return button_;
  }
  /**
   * <code>.skymouse.MouseButton button = 1;</code>
   * @return The button.
   */
  @java.lang.Override public com.skymouse.skymouseclient.proto.MouseButton getButton() {
    com.skymouse.skymouseclient.proto.MouseButton result = com.skymouse.skymouseclient.proto.MouseButton.forNumber(button_);
    return result == null ? com.skymouse.skymouseclient.proto.MouseButton.UNRECOGNIZED : result;
  }

  public static final int STATE_FIELD_NUMBER = 2;
  private int state_ = 0;
  /**
   * <code>.skymouse.ButtonState state = 2;</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override public int getStateValue() {
    return state_;
  }
  /**
   * <code>.skymouse.ButtonState state = 2;</code>
   * @return The state.
   */
  @java.lang.Override public com.skymouse.skymouseclient.proto.ButtonState getState() {
    com.skymouse.skymouseclient.proto.ButtonState result = com.skymouse.skymouseclient.proto.ButtonState.forNumber(state_);
    return result == null ? com.skymouse.skymouseclient.proto.ButtonState.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMP_MS_FIELD_NUMBER = 3;
  private long timestampMs_ = 0L;
  /**
   * <code>int64 timestamp_ms = 3;</code>
   * @return The timestampMs.
   */
  @java.lang.Override
  public long getTimestampMs() {
    return timestampMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (button_ != com.skymouse.skymouseclient.proto.MouseButton.BUTTON_UNKNOWN.getNumber()) {
      output.writeEnum(1, button_);
    }
    if (state_ != com.skymouse.skymouseclient.proto.ButtonState.STATE_UNKNOWN.getNumber()) {
      output.writeEnum(2, state_);
    }
    if (timestampMs_ != 0L) {
      output.writeInt64(3, timestampMs_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (button_ != com.skymouse.skymouseclient.proto.MouseButton.BUTTON_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, button_);
    }
    if (state_ != com.skymouse.skymouseclient.proto.ButtonState.STATE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, state_);
    }
    if (timestampMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, timestampMs_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.skymouse.skymouseclient.proto.ClickEvent)) {
      return super.equals(obj);
    }
    com.skymouse.skymouseclient.proto.ClickEvent other = (com.skymouse.skymouseclient.proto.ClickEvent) obj;

    if (button_ != other.button_) return false;
    if (state_ != other.state_) return false;
    if (getTimestampMs()
        != other.getTimestampMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUTTON_FIELD_NUMBER;
    hash = (53 * hash) + button_;
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (37 * hash) + TIMESTAMP_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestampMs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.skymouse.skymouseclient.proto.ClickEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.ClickEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.ClickEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.ClickEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.ClickEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.ClickEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.ClickEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.skymouse.skymouseclient.proto.ClickEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.skymouse.skymouseclient.proto.ClickEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.skymouse.skymouseclient.proto.ClickEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.ClickEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.skymouse.skymouseclient.proto.ClickEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.skymouse.skymouseclient.proto.ClickEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code skymouse.ClickEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:skymouse.ClickEvent)
      com.skymouse.skymouseclient.proto.ClickEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_ClickEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_ClickEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skymouse.skymouseclient.proto.ClickEvent.class, com.skymouse.skymouseclient.proto.ClickEvent.Builder.class);
    }

    // Construct using com.skymouse.skymouseclient.proto.ClickEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      button_ = 0;
      state_ = 0;
      timestampMs_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_ClickEvent_descriptor;
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ClickEvent getDefaultInstanceForType() {
      return com.skymouse.skymouseclient.proto.ClickEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ClickEvent build() {
      com.skymouse.skymouseclient.proto.ClickEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ClickEvent buildPartial() {
      com.skymouse.skymouseclient.proto.ClickEvent result = new com.skymouse.skymouseclient.proto.ClickEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.skymouse.skymouseclient.proto.ClickEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.button_ = button_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.state_ = state_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timestampMs_ = timestampMs_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.skymouse.skymouseclient.proto.ClickEvent) {
        return mergeFrom((com.skymouse.skymouseclient.proto.ClickEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.skymouse.skymouseclient.proto.ClickEvent other) {
      if (other == com.skymouse.skymouseclient.proto.ClickEvent.getDefaultInstance()) return this;
      if (other.button_ != 0) {
        setButtonValue(other.getButtonValue());
      }
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      if (other.getTimestampMs() != 0L) {
        setTimestampMs(other.getTimestampMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              button_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              state_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              timestampMs_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int button_ = 0;
    /**
     * <code>.skymouse.MouseButton button = 1;</code>
     * @return The enum numeric value on the wire for button.
     */
    @java.lang.Override public int getButtonValue() {
      return button_;
    }
    /**
     * <code>.skymouse.MouseButton button = 1;</code>
     * @param value The enum numeric value on the wire for button to set.
     * @return This builder for chaining.
     */
    public Builder setButtonValue(int value) {
      button_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.skymouse.MouseButton button = 1;</code>
     * @return The button.
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.MouseButton getButton() {
      com.skymouse.skymouseclient.proto.MouseButton result = com.skymouse.skymouseclient.proto.MouseButton.forNumber(button_);
      return result == null ? com.skymouse.skymouseclient.proto.MouseButton.UNRECOGNIZED : result;
    }
    /**
     * <code>.skymouse.MouseButton button = 1;</code>
     * @param value The button to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setButton(com.skymouse.skymouseclient.proto.MouseButton value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      button_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.skymouse.MouseButton button = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearButton() {
      bitField0_ = (bitField0_ & ~0x00000001);
      button_ = 0;
      onChanged();
      return this;
    }

    private int state_ = 0;
    /**
     * <code>.skymouse.ButtonState state = 2;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.skymouse.ButtonState state = 2;</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      state_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.skymouse.ButtonState state = 2;</code>
     * @return The state.
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ButtonState getState() {
      com.skymouse.skymouseclient.proto.ButtonState result = com.skymouse.skymouseclient.proto.ButtonState.forNumber(state_);
      return result == null ? com.skymouse.skymouseclient.proto.ButtonState.UNRECOGNIZED : result;
    }
    /**
     * <code>.skymouse.ButtonState state = 2;</code>
     * @param value The state to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setState(com.skymouse.skymouseclient.proto.ButtonState value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.skymouse.ButtonState state = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000002);
      state_ = 0;
      onChanged();
      return this;
    }

    private long timestampMs_ ;
    /**
     * <code>int64 timestamp_ms = 3;</code>
     * @return The timestampMs.
     */
    @java.lang.Override
    public long getTimestampMs() {
      return timestampMs_;
    }
    /**
     * <code>int64 timestamp_ms = 3;</code>
     * @param value The timestampMs to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampMs(long value) {

      timestampMs_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp_ms = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampMs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timestampMs_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:skymouse.ClickEvent)
  }

  // @@protoc_insertion_point(class_scope:skymouse.ClickEvent)
  private static final com.skymouse.skymouseclient.proto.ClickEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.skymouse.skymouseclient.proto.ClickEvent();
  }

  public static com.skymouse.skymouseclient.proto.ClickEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClickEvent>
      PARSER = new com.google.protobuf.AbstractParser<ClickEvent>() {
    @java.lang.Override
    public ClickEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClickEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClickEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.skymouse.skymouseclient.proto.ClickEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

