// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializeclickEvent")
public inline fun clickEvent(block: com.skymouse.skymouseclient.proto.ClickEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.ClickEvent =
  com.skymouse.skymouseclient.proto.ClickEventKt.Dsl._create(com.skymouse.skymouseclient.proto.ClickEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.ClickEvent`
 */
public object ClickEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.ClickEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.ClickEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.ClickEvent = _builder.build()

    /**
     * `.skymouse.MouseButton button = 1;`
     */
    public var button: com.skymouse.skymouseclient.proto.MouseButton
      @kotlin.jvm.JvmName("getButton")
        get() = _builder.button
      @kotlin.jvm.JvmName("setButton")
        set(value) {
        _builder.button = value
      }
    public var buttonValue: kotlin.Int
      @kotlin.jvm.JvmName("getButtonValue")
        get() = _builder.buttonValue
      @kotlin.jvm.JvmName("setButtonValue")
        set(value) {
        _builder.buttonValue = value
      }
    /**
     * `.skymouse.MouseButton button = 1;`
     */
    public fun clearButton() {
      _builder.clearButton()
    }

    /**
     * `.skymouse.ButtonState state = 2;`
     */
    public var state: com.skymouse.skymouseclient.proto.ButtonState
      @kotlin.jvm.JvmName("getState")
        get() = _builder.state
      @kotlin.jvm.JvmName("setState")
        set(value) {
        _builder.state = value
      }
    public var stateValue: kotlin.Int
      @kotlin.jvm.JvmName("getStateValue")
        get() = _builder.stateValue
      @kotlin.jvm.JvmName("setStateValue")
        set(value) {
        _builder.stateValue = value
      }
    /**
     * `.skymouse.ButtonState state = 2;`
     */
    public fun clearState() {
      _builder.clearState()
    }

    /**
     * `int64 timestamp_ms = 3;`
     */
    public var timestampMs: kotlin.Long
      @kotlin.jvm.JvmName("getTimestampMs")
        get() = _builder.timestampMs
      @kotlin.jvm.JvmName("setTimestampMs")
        set(value) {
        _builder.timestampMs = value
      }
    /**
     * `int64 timestamp_ms = 3;`
     */
    public fun clearTimestampMs() {
      _builder.clearTimestampMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.ClickEvent.copy(block: `com.skymouse.skymouseclient.proto`.ClickEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.ClickEvent =
  `com.skymouse.skymouseclient.proto`.ClickEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

