// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface ClickEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.ClickEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.skymouse.MouseButton button = 1;</code>
   * @return The enum numeric value on the wire for button.
   */
  int getButtonValue();
  /**
   * <code>.skymouse.MouseButton button = 1;</code>
   * @return The button.
   */
  com.skymouse.skymouseclient.proto.MouseButton getButton();

  /**
   * <code>.skymouse.ButtonState state = 2;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.skymouse.ButtonState state = 2;</code>
   * @return The state.
   */
  com.skymouse.skymouseclient.proto.ButtonState getState();

  /**
   * <code>int64 timestamp_ms = 3;</code>
   * @return The timestampMs.
   */
  long getTimestampMs();
}
