// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializeclientHello")
public inline fun clientHello(block: com.skymouse.skymouseclient.proto.ClientHelloKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.ClientHello =
  com.skymouse.skymouseclient.proto.ClientHelloKt.Dsl._create(com.skymouse.skymouseclient.proto.ClientHello.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.ClientHello`
 */
public object ClientHelloKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.ClientHello.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.ClientHello.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.ClientHello = _builder.build()

    /**
     * `string client_version = 1;`
     */
    public var clientVersion: kotlin.String
      @kotlin.jvm.JvmName("getClientVersion")
        get() = _builder.clientVersion
      @kotlin.jvm.JvmName("setClientVersion")
        set(value) {
        _builder.clientVersion = value
      }
    /**
     * `string client_version = 1;`
     */
    public fun clearClientVersion() {
      _builder.clearClientVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.ClientHello.copy(block: `com.skymouse.skymouseclient.proto`.ClientHelloKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.ClientHello =
  `com.skymouse.skymouseclient.proto`.ClientHelloKt.Dsl._create(this.toBuilder()).apply { block() }._build()

