// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface ClientHelloOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.ClientHello)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string client_version = 1;</code>
   * @return The clientVersion.
   */
  java.lang.String getClientVersion();
  /**
   * <code>string client_version = 1;</code>
   * @return The bytes for clientVersion.
   */
  com.google.protobuf.ByteString
      getClientVersionBytes();
}
