// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializeclipboardShareEvent")
public inline fun clipboardShareEvent(block: com.skymouse.skymouseclient.proto.ClipboardShareEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.ClipboardShareEvent =
  com.skymouse.skymouseclient.proto.ClipboardShareEventKt.Dsl._create(com.skymouse.skymouseclient.proto.ClipboardShareEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.ClipboardShareEvent`
 */
public object ClipboardShareEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.ClipboardShareEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.ClipboardShareEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.ClipboardShareEvent = _builder.build()

    /**
     * ```
     * for images in future updates
     * ```
     *
     * `string text = 1;`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * ```
     * for images in future updates
     * ```
     *
     * `string text = 1;`
     */
    public fun clearText() {
      _builder.clearText()
    }
    /**
     * ```
     * for images in future updates
     * ```
     *
     * `string text = 1;`
     * @return Whether the text field is set.
     */
    public fun hasText(): kotlin.Boolean {
      return _builder.hasText()
    }
    public val contentCase: com.skymouse.skymouseclient.proto.ClipboardShareEvent.ContentCase
    @kotlin.jvm.JvmName("getContentCase")
      get() = _builder.getContentCase()

    public fun clearContent() {
      _builder.clearContent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.ClipboardShareEvent.copy(block: `com.skymouse.skymouseclient.proto`.ClipboardShareEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.ClipboardShareEvent =
  `com.skymouse.skymouseclient.proto`.ClipboardShareEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

