// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface ClipboardShareEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.ClipboardShareEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * for images in future updates
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <pre>
   * for images in future updates
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <pre>
   * for images in future updates
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  com.skymouse.skymouseclient.proto.ClipboardShareEvent.ContentCase getContentCase();
}
