// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializecurrentCursorScaleAnswer")
public inline fun currentCursorScaleAnswer(block: com.skymouse.skymouseclient.proto.CurrentCursorScaleAnswerKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.CurrentCursorScaleAnswer =
  com.skymouse.skymouseclient.proto.CurrentCursorScaleAnswerKt.Dsl._create(com.skymouse.skymouseclient.proto.CurrentCursorScaleAnswer.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.CurrentCursorScaleAnswer`
 */
public object CurrentCursorScaleAnswerKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.CurrentCursorScaleAnswer.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.CurrentCursorScaleAnswer.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.CurrentCursorScaleAnswer = _builder.build()

    /**
     * `int32 current_cursor_scale = 1;`
     */
    public var currentCursorScale: kotlin.Int
      @kotlin.jvm.JvmName("getCurrentCursorScale")
        get() = _builder.currentCursorScale
      @kotlin.jvm.JvmName("setCurrentCursorScale")
        set(value) {
        _builder.currentCursorScale = value
      }
    /**
     * `int32 current_cursor_scale = 1;`
     */
    public fun clearCurrentCursorScale() {
      _builder.clearCurrentCursorScale()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.CurrentCursorScaleAnswer.copy(block: `com.skymouse.skymouseclient.proto`.CurrentCursorScaleAnswerKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.CurrentCursorScaleAnswer =
  `com.skymouse.skymouseclient.proto`.CurrentCursorScaleAnswerKt.Dsl._create(this.toBuilder()).apply { block() }._build()

