// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface CurrentCursorScaleAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.CurrentCursorScaleAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 current_cursor_scale = 1;</code>
   * @return The currentCursorScale.
   */
  int getCurrentCursorScale();
}
