// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializeemulatorEvent")
public inline fun emulatorEvent(block: com.skymouse.skymouseclient.proto.EmulatorEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.EmulatorEvent =
  com.skymouse.skymouseclient.proto.EmulatorEventKt.Dsl._create(com.skymouse.skymouseclient.proto.EmulatorEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.EmulatorEvent`
 */
public object EmulatorEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.EmulatorEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.EmulatorEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.EmulatorEvent = _builder.build()

    /**
     * `.skymouse.MouseEvent mouse = 1;`
     */
    public var mouse: com.skymouse.skymouseclient.proto.MouseEvent
      @kotlin.jvm.JvmName("getMouse")
        get() = _builder.mouse
      @kotlin.jvm.JvmName("setMouse")
        set(value) {
        _builder.mouse = value
      }
    /**
     * `.skymouse.MouseEvent mouse = 1;`
     */
    public fun clearMouse() {
      _builder.clearMouse()
    }
    /**
     * `.skymouse.MouseEvent mouse = 1;`
     * @return Whether the mouse field is set.
     */
    public fun hasMouse(): kotlin.Boolean {
      return _builder.hasMouse()
    }

    /**
     * `.skymouse.ClickEvent click = 2;`
     */
    public var click: com.skymouse.skymouseclient.proto.ClickEvent
      @kotlin.jvm.JvmName("getClick")
        get() = _builder.click
      @kotlin.jvm.JvmName("setClick")
        set(value) {
        _builder.click = value
      }
    /**
     * `.skymouse.ClickEvent click = 2;`
     */
    public fun clearClick() {
      _builder.clearClick()
    }
    /**
     * `.skymouse.ClickEvent click = 2;`
     * @return Whether the click field is set.
     */
    public fun hasClick(): kotlin.Boolean {
      return _builder.hasClick()
    }

    /**
     * `.skymouse.ScrollEvent scroll = 3;`
     */
    public var scroll: com.skymouse.skymouseclient.proto.ScrollEvent
      @kotlin.jvm.JvmName("getScroll")
        get() = _builder.scroll
      @kotlin.jvm.JvmName("setScroll")
        set(value) {
        _builder.scroll = value
      }
    /**
     * `.skymouse.ScrollEvent scroll = 3;`
     */
    public fun clearScroll() {
      _builder.clearScroll()
    }
    /**
     * `.skymouse.ScrollEvent scroll = 3;`
     * @return Whether the scroll field is set.
     */
    public fun hasScroll(): kotlin.Boolean {
      return _builder.hasScroll()
    }

    /**
     * `.skymouse.KeyboardStringEvent keyboard_string_event = 4;`
     */
    public var keyboardStringEvent: com.skymouse.skymouseclient.proto.KeyboardStringEvent
      @kotlin.jvm.JvmName("getKeyboardStringEvent")
        get() = _builder.keyboardStringEvent
      @kotlin.jvm.JvmName("setKeyboardStringEvent")
        set(value) {
        _builder.keyboardStringEvent = value
      }
    /**
     * `.skymouse.KeyboardStringEvent keyboard_string_event = 4;`
     */
    public fun clearKeyboardStringEvent() {
      _builder.clearKeyboardStringEvent()
    }
    /**
     * `.skymouse.KeyboardStringEvent keyboard_string_event = 4;`
     * @return Whether the keyboardStringEvent field is set.
     */
    public fun hasKeyboardStringEvent(): kotlin.Boolean {
      return _builder.hasKeyboardStringEvent()
    }

    /**
     * `.skymouse.KeyboardTapEvent keyboard_tap_event = 5;`
     */
    public var keyboardTapEvent: com.skymouse.skymouseclient.proto.KeyboardTapEvent
      @kotlin.jvm.JvmName("getKeyboardTapEvent")
        get() = _builder.keyboardTapEvent
      @kotlin.jvm.JvmName("setKeyboardTapEvent")
        set(value) {
        _builder.keyboardTapEvent = value
      }
    /**
     * `.skymouse.KeyboardTapEvent keyboard_tap_event = 5;`
     */
    public fun clearKeyboardTapEvent() {
      _builder.clearKeyboardTapEvent()
    }
    /**
     * `.skymouse.KeyboardTapEvent keyboard_tap_event = 5;`
     * @return Whether the keyboardTapEvent field is set.
     */
    public fun hasKeyboardTapEvent(): kotlin.Boolean {
      return _builder.hasKeyboardTapEvent()
    }
    public val eventCase: com.skymouse.skymouseclient.proto.EmulatorEvent.EventCase
    @kotlin.jvm.JvmName("getEventCase")
      get() = _builder.getEventCase()

    public fun clearEvent() {
      _builder.clearEvent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.EmulatorEvent.copy(block: `com.skymouse.skymouseclient.proto`.EmulatorEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.EmulatorEvent =
  `com.skymouse.skymouseclient.proto`.EmulatorEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder.mouseOrNull: com.skymouse.skymouseclient.proto.MouseEvent?
  get() = if (hasMouse()) getMouse() else null

public val com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder.clickOrNull: com.skymouse.skymouseclient.proto.ClickEvent?
  get() = if (hasClick()) getClick() else null

public val com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder.scrollOrNull: com.skymouse.skymouseclient.proto.ScrollEvent?
  get() = if (hasScroll()) getScroll() else null

public val com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder.keyboardStringEventOrNull: com.skymouse.skymouseclient.proto.KeyboardStringEvent?
  get() = if (hasKeyboardStringEvent()) getKeyboardStringEvent() else null

public val com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder.keyboardTapEventOrNull: com.skymouse.skymouseclient.proto.KeyboardTapEvent?
  get() = if (hasKeyboardTapEvent()) getKeyboardTapEvent() else null

