// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

/**
 * Protobuf type {@code skymouse.EmulatorEvent}
 */
@com.google.protobuf.Generated
public final class EmulatorEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:skymouse.EmulatorEvent)
    EmulatorEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "EmulatorEvent");
  }
  // Use EmulatorEvent.newBuilder() to construct.
  private EmulatorEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EmulatorEvent() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_EmulatorEvent_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_EmulatorEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_EmulatorEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.skymouse.skymouseclient.proto.EmulatorEvent.class, com.skymouse.skymouseclient.proto.EmulatorEvent.Builder.class);
  }

  private int eventCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object event_;
  public enum EventCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    MOUSE(1),
    CLICK(2),
    SCROLL(3),
    EVENT_NOT_SET(0);
    private final int value;
    private EventCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventCase forNumber(int value) {
      switch (value) {
        case 1: return MOUSE;
        case 2: return CLICK;
        case 3: return SCROLL;
        case 0: return EVENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EventCase
  getEventCase() {
    return EventCase.forNumber(
        eventCase_);
  }

  public static final int MOUSE_FIELD_NUMBER = 1;
  /**
   * <code>.skymouse.MouseEvent mouse = 1;</code>
   * @return Whether the mouse field is set.
   */
  @java.lang.Override
  public boolean hasMouse() {
    return eventCase_ == 1;
  }
  /**
   * <code>.skymouse.MouseEvent mouse = 1;</code>
   * @return The mouse.
   */
  @java.lang.Override
  public com.skymouse.skymouseclient.proto.MouseEvent getMouse() {
    if (eventCase_ == 1) {
       return (com.skymouse.skymouseclient.proto.MouseEvent) event_;
    }
    return com.skymouse.skymouseclient.proto.MouseEvent.getDefaultInstance();
  }
  /**
   * <code>.skymouse.MouseEvent mouse = 1;</code>
   */
  @java.lang.Override
  public com.skymouse.skymouseclient.proto.MouseEventOrBuilder getMouseOrBuilder() {
    if (eventCase_ == 1) {
       return (com.skymouse.skymouseclient.proto.MouseEvent) event_;
    }
    return com.skymouse.skymouseclient.proto.MouseEvent.getDefaultInstance();
  }

  public static final int CLICK_FIELD_NUMBER = 2;
  /**
   * <code>.skymouse.ClickEvent click = 2;</code>
   * @return Whether the click field is set.
   */
  @java.lang.Override
  public boolean hasClick() {
    return eventCase_ == 2;
  }
  /**
   * <code>.skymouse.ClickEvent click = 2;</code>
   * @return The click.
   */
  @java.lang.Override
  public com.skymouse.skymouseclient.proto.ClickEvent getClick() {
    if (eventCase_ == 2) {
       return (com.skymouse.skymouseclient.proto.ClickEvent) event_;
    }
    return com.skymouse.skymouseclient.proto.ClickEvent.getDefaultInstance();
  }
  /**
   * <code>.skymouse.ClickEvent click = 2;</code>
   */
  @java.lang.Override
  public com.skymouse.skymouseclient.proto.ClickEventOrBuilder getClickOrBuilder() {
    if (eventCase_ == 2) {
       return (com.skymouse.skymouseclient.proto.ClickEvent) event_;
    }
    return com.skymouse.skymouseclient.proto.ClickEvent.getDefaultInstance();
  }

  public static final int SCROLL_FIELD_NUMBER = 3;
  /**
   * <code>.skymouse.ScrollEvent scroll = 3;</code>
   * @return Whether the scroll field is set.
   */
  @java.lang.Override
  public boolean hasScroll() {
    return eventCase_ == 3;
  }
  /**
   * <code>.skymouse.ScrollEvent scroll = 3;</code>
   * @return The scroll.
   */
  @java.lang.Override
  public com.skymouse.skymouseclient.proto.ScrollEvent getScroll() {
    if (eventCase_ == 3) {
       return (com.skymouse.skymouseclient.proto.ScrollEvent) event_;
    }
    return com.skymouse.skymouseclient.proto.ScrollEvent.getDefaultInstance();
  }
  /**
   * <code>.skymouse.ScrollEvent scroll = 3;</code>
   */
  @java.lang.Override
  public com.skymouse.skymouseclient.proto.ScrollEventOrBuilder getScrollOrBuilder() {
    if (eventCase_ == 3) {
       return (com.skymouse.skymouseclient.proto.ScrollEvent) event_;
    }
    return com.skymouse.skymouseclient.proto.ScrollEvent.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventCase_ == 1) {
      output.writeMessage(1, (com.skymouse.skymouseclient.proto.MouseEvent) event_);
    }
    if (eventCase_ == 2) {
      output.writeMessage(2, (com.skymouse.skymouseclient.proto.ClickEvent) event_);
    }
    if (eventCase_ == 3) {
      output.writeMessage(3, (com.skymouse.skymouseclient.proto.ScrollEvent) event_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (eventCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.skymouse.skymouseclient.proto.MouseEvent) event_);
    }
    if (eventCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.skymouse.skymouseclient.proto.ClickEvent) event_);
    }
    if (eventCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.skymouse.skymouseclient.proto.ScrollEvent) event_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.skymouse.skymouseclient.proto.EmulatorEvent)) {
      return super.equals(obj);
    }
    com.skymouse.skymouseclient.proto.EmulatorEvent other = (com.skymouse.skymouseclient.proto.EmulatorEvent) obj;

    if (!getEventCase().equals(other.getEventCase())) return false;
    switch (eventCase_) {
      case 1:
        if (!getMouse()
            .equals(other.getMouse())) return false;
        break;
      case 2:
        if (!getClick()
            .equals(other.getClick())) return false;
        break;
      case 3:
        if (!getScroll()
            .equals(other.getScroll())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (eventCase_) {
      case 1:
        hash = (37 * hash) + MOUSE_FIELD_NUMBER;
        hash = (53 * hash) + getMouse().hashCode();
        break;
      case 2:
        hash = (37 * hash) + CLICK_FIELD_NUMBER;
        hash = (53 * hash) + getClick().hashCode();
        break;
      case 3:
        hash = (37 * hash) + SCROLL_FIELD_NUMBER;
        hash = (53 * hash) + getScroll().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.skymouse.skymouseclient.proto.EmulatorEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.EmulatorEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.EmulatorEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.EmulatorEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.EmulatorEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.EmulatorEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.EmulatorEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.skymouse.skymouseclient.proto.EmulatorEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.skymouse.skymouseclient.proto.EmulatorEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.skymouse.skymouseclient.proto.EmulatorEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.EmulatorEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.skymouse.skymouseclient.proto.EmulatorEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.skymouse.skymouseclient.proto.EmulatorEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code skymouse.EmulatorEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:skymouse.EmulatorEvent)
      com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_EmulatorEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_EmulatorEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skymouse.skymouseclient.proto.EmulatorEvent.class, com.skymouse.skymouseclient.proto.EmulatorEvent.Builder.class);
    }

    // Construct using com.skymouse.skymouseclient.proto.EmulatorEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (mouseBuilder_ != null) {
        mouseBuilder_.clear();
      }
      if (clickBuilder_ != null) {
        clickBuilder_.clear();
      }
      if (scrollBuilder_ != null) {
        scrollBuilder_.clear();
      }
      eventCase_ = 0;
      event_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_EmulatorEvent_descriptor;
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.EmulatorEvent getDefaultInstanceForType() {
      return com.skymouse.skymouseclient.proto.EmulatorEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.EmulatorEvent build() {
      com.skymouse.skymouseclient.proto.EmulatorEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.EmulatorEvent buildPartial() {
      com.skymouse.skymouseclient.proto.EmulatorEvent result = new com.skymouse.skymouseclient.proto.EmulatorEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.skymouse.skymouseclient.proto.EmulatorEvent result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.skymouse.skymouseclient.proto.EmulatorEvent result) {
      result.eventCase_ = eventCase_;
      result.event_ = this.event_;
      if (eventCase_ == 1 &&
          mouseBuilder_ != null) {
        result.event_ = mouseBuilder_.build();
      }
      if (eventCase_ == 2 &&
          clickBuilder_ != null) {
        result.event_ = clickBuilder_.build();
      }
      if (eventCase_ == 3 &&
          scrollBuilder_ != null) {
        result.event_ = scrollBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.skymouse.skymouseclient.proto.EmulatorEvent) {
        return mergeFrom((com.skymouse.skymouseclient.proto.EmulatorEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.skymouse.skymouseclient.proto.EmulatorEvent other) {
      if (other == com.skymouse.skymouseclient.proto.EmulatorEvent.getDefaultInstance()) return this;
      switch (other.getEventCase()) {
        case MOUSE: {
          mergeMouse(other.getMouse());
          break;
        }
        case CLICK: {
          mergeClick(other.getClick());
          break;
        }
        case SCROLL: {
          mergeScroll(other.getScroll());
          break;
        }
        case EVENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetMouseFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetClickFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetScrollFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int eventCase_ = 0;
    private java.lang.Object event_;
    public EventCase
        getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public Builder clearEvent() {
      eventCase_ = 0;
      event_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.skymouse.skymouseclient.proto.MouseEvent, com.skymouse.skymouseclient.proto.MouseEvent.Builder, com.skymouse.skymouseclient.proto.MouseEventOrBuilder> mouseBuilder_;
    /**
     * <code>.skymouse.MouseEvent mouse = 1;</code>
     * @return Whether the mouse field is set.
     */
    @java.lang.Override
    public boolean hasMouse() {
      return eventCase_ == 1;
    }
    /**
     * <code>.skymouse.MouseEvent mouse = 1;</code>
     * @return The mouse.
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.MouseEvent getMouse() {
      if (mouseBuilder_ == null) {
        if (eventCase_ == 1) {
          return (com.skymouse.skymouseclient.proto.MouseEvent) event_;
        }
        return com.skymouse.skymouseclient.proto.MouseEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 1) {
          return mouseBuilder_.getMessage();
        }
        return com.skymouse.skymouseclient.proto.MouseEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.skymouse.MouseEvent mouse = 1;</code>
     */
    public Builder setMouse(com.skymouse.skymouseclient.proto.MouseEvent value) {
      if (mouseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        mouseBuilder_.setMessage(value);
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.skymouse.MouseEvent mouse = 1;</code>
     */
    public Builder setMouse(
        com.skymouse.skymouseclient.proto.MouseEvent.Builder builderForValue) {
      if (mouseBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        mouseBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.skymouse.MouseEvent mouse = 1;</code>
     */
    public Builder mergeMouse(com.skymouse.skymouseclient.proto.MouseEvent value) {
      if (mouseBuilder_ == null) {
        if (eventCase_ == 1 &&
            event_ != com.skymouse.skymouseclient.proto.MouseEvent.getDefaultInstance()) {
          event_ = com.skymouse.skymouseclient.proto.MouseEvent.newBuilder((com.skymouse.skymouseclient.proto.MouseEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 1) {
          mouseBuilder_.mergeFrom(value);
        } else {
          mouseBuilder_.setMessage(value);
        }
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.skymouse.MouseEvent mouse = 1;</code>
     */
    public Builder clearMouse() {
      if (mouseBuilder_ == null) {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
        }
        mouseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.skymouse.MouseEvent mouse = 1;</code>
     */
    public com.skymouse.skymouseclient.proto.MouseEvent.Builder getMouseBuilder() {
      return internalGetMouseFieldBuilder().getBuilder();
    }
    /**
     * <code>.skymouse.MouseEvent mouse = 1;</code>
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.MouseEventOrBuilder getMouseOrBuilder() {
      if ((eventCase_ == 1) && (mouseBuilder_ != null)) {
        return mouseBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 1) {
          return (com.skymouse.skymouseclient.proto.MouseEvent) event_;
        }
        return com.skymouse.skymouseclient.proto.MouseEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.skymouse.MouseEvent mouse = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.skymouse.skymouseclient.proto.MouseEvent, com.skymouse.skymouseclient.proto.MouseEvent.Builder, com.skymouse.skymouseclient.proto.MouseEventOrBuilder> 
        internalGetMouseFieldBuilder() {
      if (mouseBuilder_ == null) {
        if (!(eventCase_ == 1)) {
          event_ = com.skymouse.skymouseclient.proto.MouseEvent.getDefaultInstance();
        }
        mouseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.skymouse.skymouseclient.proto.MouseEvent, com.skymouse.skymouseclient.proto.MouseEvent.Builder, com.skymouse.skymouseclient.proto.MouseEventOrBuilder>(
                (com.skymouse.skymouseclient.proto.MouseEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 1;
      onChanged();
      return mouseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.skymouse.skymouseclient.proto.ClickEvent, com.skymouse.skymouseclient.proto.ClickEvent.Builder, com.skymouse.skymouseclient.proto.ClickEventOrBuilder> clickBuilder_;
    /**
     * <code>.skymouse.ClickEvent click = 2;</code>
     * @return Whether the click field is set.
     */
    @java.lang.Override
    public boolean hasClick() {
      return eventCase_ == 2;
    }
    /**
     * <code>.skymouse.ClickEvent click = 2;</code>
     * @return The click.
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ClickEvent getClick() {
      if (clickBuilder_ == null) {
        if (eventCase_ == 2) {
          return (com.skymouse.skymouseclient.proto.ClickEvent) event_;
        }
        return com.skymouse.skymouseclient.proto.ClickEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 2) {
          return clickBuilder_.getMessage();
        }
        return com.skymouse.skymouseclient.proto.ClickEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.skymouse.ClickEvent click = 2;</code>
     */
    public Builder setClick(com.skymouse.skymouseclient.proto.ClickEvent value) {
      if (clickBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        clickBuilder_.setMessage(value);
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.skymouse.ClickEvent click = 2;</code>
     */
    public Builder setClick(
        com.skymouse.skymouseclient.proto.ClickEvent.Builder builderForValue) {
      if (clickBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        clickBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.skymouse.ClickEvent click = 2;</code>
     */
    public Builder mergeClick(com.skymouse.skymouseclient.proto.ClickEvent value) {
      if (clickBuilder_ == null) {
        if (eventCase_ == 2 &&
            event_ != com.skymouse.skymouseclient.proto.ClickEvent.getDefaultInstance()) {
          event_ = com.skymouse.skymouseclient.proto.ClickEvent.newBuilder((com.skymouse.skymouseclient.proto.ClickEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 2) {
          clickBuilder_.mergeFrom(value);
        } else {
          clickBuilder_.setMessage(value);
        }
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.skymouse.ClickEvent click = 2;</code>
     */
    public Builder clearClick() {
      if (clickBuilder_ == null) {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
        }
        clickBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.skymouse.ClickEvent click = 2;</code>
     */
    public com.skymouse.skymouseclient.proto.ClickEvent.Builder getClickBuilder() {
      return internalGetClickFieldBuilder().getBuilder();
    }
    /**
     * <code>.skymouse.ClickEvent click = 2;</code>
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ClickEventOrBuilder getClickOrBuilder() {
      if ((eventCase_ == 2) && (clickBuilder_ != null)) {
        return clickBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 2) {
          return (com.skymouse.skymouseclient.proto.ClickEvent) event_;
        }
        return com.skymouse.skymouseclient.proto.ClickEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.skymouse.ClickEvent click = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.skymouse.skymouseclient.proto.ClickEvent, com.skymouse.skymouseclient.proto.ClickEvent.Builder, com.skymouse.skymouseclient.proto.ClickEventOrBuilder> 
        internalGetClickFieldBuilder() {
      if (clickBuilder_ == null) {
        if (!(eventCase_ == 2)) {
          event_ = com.skymouse.skymouseclient.proto.ClickEvent.getDefaultInstance();
        }
        clickBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.skymouse.skymouseclient.proto.ClickEvent, com.skymouse.skymouseclient.proto.ClickEvent.Builder, com.skymouse.skymouseclient.proto.ClickEventOrBuilder>(
                (com.skymouse.skymouseclient.proto.ClickEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 2;
      onChanged();
      return clickBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.skymouse.skymouseclient.proto.ScrollEvent, com.skymouse.skymouseclient.proto.ScrollEvent.Builder, com.skymouse.skymouseclient.proto.ScrollEventOrBuilder> scrollBuilder_;
    /**
     * <code>.skymouse.ScrollEvent scroll = 3;</code>
     * @return Whether the scroll field is set.
     */
    @java.lang.Override
    public boolean hasScroll() {
      return eventCase_ == 3;
    }
    /**
     * <code>.skymouse.ScrollEvent scroll = 3;</code>
     * @return The scroll.
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ScrollEvent getScroll() {
      if (scrollBuilder_ == null) {
        if (eventCase_ == 3) {
          return (com.skymouse.skymouseclient.proto.ScrollEvent) event_;
        }
        return com.skymouse.skymouseclient.proto.ScrollEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 3) {
          return scrollBuilder_.getMessage();
        }
        return com.skymouse.skymouseclient.proto.ScrollEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.skymouse.ScrollEvent scroll = 3;</code>
     */
    public Builder setScroll(com.skymouse.skymouseclient.proto.ScrollEvent value) {
      if (scrollBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        scrollBuilder_.setMessage(value);
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.skymouse.ScrollEvent scroll = 3;</code>
     */
    public Builder setScroll(
        com.skymouse.skymouseclient.proto.ScrollEvent.Builder builderForValue) {
      if (scrollBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        scrollBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.skymouse.ScrollEvent scroll = 3;</code>
     */
    public Builder mergeScroll(com.skymouse.skymouseclient.proto.ScrollEvent value) {
      if (scrollBuilder_ == null) {
        if (eventCase_ == 3 &&
            event_ != com.skymouse.skymouseclient.proto.ScrollEvent.getDefaultInstance()) {
          event_ = com.skymouse.skymouseclient.proto.ScrollEvent.newBuilder((com.skymouse.skymouseclient.proto.ScrollEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 3) {
          scrollBuilder_.mergeFrom(value);
        } else {
          scrollBuilder_.setMessage(value);
        }
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.skymouse.ScrollEvent scroll = 3;</code>
     */
    public Builder clearScroll() {
      if (scrollBuilder_ == null) {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
        }
        scrollBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.skymouse.ScrollEvent scroll = 3;</code>
     */
    public com.skymouse.skymouseclient.proto.ScrollEvent.Builder getScrollBuilder() {
      return internalGetScrollFieldBuilder().getBuilder();
    }
    /**
     * <code>.skymouse.ScrollEvent scroll = 3;</code>
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ScrollEventOrBuilder getScrollOrBuilder() {
      if ((eventCase_ == 3) && (scrollBuilder_ != null)) {
        return scrollBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 3) {
          return (com.skymouse.skymouseclient.proto.ScrollEvent) event_;
        }
        return com.skymouse.skymouseclient.proto.ScrollEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.skymouse.ScrollEvent scroll = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.skymouse.skymouseclient.proto.ScrollEvent, com.skymouse.skymouseclient.proto.ScrollEvent.Builder, com.skymouse.skymouseclient.proto.ScrollEventOrBuilder> 
        internalGetScrollFieldBuilder() {
      if (scrollBuilder_ == null) {
        if (!(eventCase_ == 3)) {
          event_ = com.skymouse.skymouseclient.proto.ScrollEvent.getDefaultInstance();
        }
        scrollBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.skymouse.skymouseclient.proto.ScrollEvent, com.skymouse.skymouseclient.proto.ScrollEvent.Builder, com.skymouse.skymouseclient.proto.ScrollEventOrBuilder>(
                (com.skymouse.skymouseclient.proto.ScrollEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 3;
      onChanged();
      return scrollBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:skymouse.EmulatorEvent)
  }

  // @@protoc_insertion_point(class_scope:skymouse.EmulatorEvent)
  private static final com.skymouse.skymouseclient.proto.EmulatorEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.skymouse.skymouseclient.proto.EmulatorEvent();
  }

  public static com.skymouse.skymouseclient.proto.EmulatorEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmulatorEvent>
      PARSER = new com.google.protobuf.AbstractParser<EmulatorEvent>() {
    @java.lang.Override
    public EmulatorEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmulatorEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmulatorEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.skymouse.skymouseclient.proto.EmulatorEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

