// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface GetCursorScaleEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.GetCursorScaleEvent)
    com.google.protobuf.MessageOrBuilder {
}
