// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializegetCursorScaleEvent")
public inline fun getCursorScaleEvent(block: com.skymouse.skymouseclient.proto.GetCursorScaleEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.GetCursorScaleEvent =
  com.skymouse.skymouseclient.proto.GetCursorScaleEventKt.Dsl._create(com.skymouse.skymouseclient.proto.GetCursorScaleEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.GetCursorScaleEvent`
 */
public object GetCursorScaleEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.GetCursorScaleEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.GetCursorScaleEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.GetCursorScaleEvent = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.GetCursorScaleEvent.copy(block: `com.skymouse.skymouseclient.proto`.GetCursorScaleEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.GetCursorScaleEvent =
  `com.skymouse.skymouseclient.proto`.GetCursorScaleEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

