// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

/**
 * Protobuf enum {@code skymouse.HapticEventType}
 */
@com.google.protobuf.Generated
public enum HapticEventType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>EVENT_UNKNOWN = 0;</code>
   */
  EVENT_UNKNOWN(0),
  /**
   * <code>EVENT_BORDER_CROSSING = 1;</code>
   */
  EVENT_BORDER_CROSSING(1),
  /**
   * <code>EVENT_EDGE_HIT = 2;</code>
   */
  EVENT_EDGE_HIT(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "HapticEventType");
  }
  /**
   * <code>EVENT_UNKNOWN = 0;</code>
   */
  public static final int EVENT_UNKNOWN_VALUE = 0;
  /**
   * <code>EVENT_BORDER_CROSSING = 1;</code>
   */
  public static final int EVENT_BORDER_CROSSING_VALUE = 1;
  /**
   * <code>EVENT_EDGE_HIT = 2;</code>
   */
  public static final int EVENT_EDGE_HIT_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static HapticEventType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static HapticEventType forNumber(int value) {
    switch (value) {
      case 0: return EVENT_UNKNOWN;
      case 1: return EVENT_BORDER_CROSSING;
      case 2: return EVENT_EDGE_HIT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<HapticEventType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      HapticEventType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<HapticEventType>() {
          public HapticEventType findValueByNumber(int number) {
            return HapticEventType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.skymouse.skymouseclient.proto.Skymouse.getDescriptor().getEnumType(2);
  }

  private static final HapticEventType[] VALUES = values();

  public static HapticEventType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private HapticEventType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:skymouse.HapticEventType)
}

