// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializekeyboardTapEvent")
public inline fun keyboardTapEvent(block: com.skymouse.skymouseclient.proto.KeyboardTapEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.KeyboardTapEvent =
  com.skymouse.skymouseclient.proto.KeyboardTapEventKt.Dsl._create(com.skymouse.skymouseclient.proto.KeyboardTapEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.KeyboardTapEvent`
 */
public object KeyboardTapEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.KeyboardTapEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.KeyboardTapEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.KeyboardTapEvent = _builder.build()

    /**
     * `.skymouse.KeyboardKey key = 1;`
     */
    public var key: com.skymouse.skymouseclient.proto.KeyboardKey
      @kotlin.jvm.JvmName("getKey")
        get() = _builder.key
      @kotlin.jvm.JvmName("setKey")
        set(value) {
        _builder.key = value
      }
    public var keyValue: kotlin.Int
      @kotlin.jvm.JvmName("getKeyValue")
        get() = _builder.keyValue
      @kotlin.jvm.JvmName("setKeyValue")
        set(value) {
        _builder.keyValue = value
      }
    /**
     * `.skymouse.KeyboardKey key = 1;`
     */
    public fun clearKey() {
      _builder.clearKey()
    }

    /**
     * `.skymouse.ButtonState state = 2;`
     */
    public var state: com.skymouse.skymouseclient.proto.ButtonState
      @kotlin.jvm.JvmName("getState")
        get() = _builder.state
      @kotlin.jvm.JvmName("setState")
        set(value) {
        _builder.state = value
      }
    public var stateValue: kotlin.Int
      @kotlin.jvm.JvmName("getStateValue")
        get() = _builder.stateValue
      @kotlin.jvm.JvmName("setStateValue")
        set(value) {
        _builder.stateValue = value
      }
    /**
     * `.skymouse.ButtonState state = 2;`
     */
    public fun clearState() {
      _builder.clearState()
    }

    /**
     * `int64 timestamp_ms = 3;`
     */
    public var timestampMs: kotlin.Long
      @kotlin.jvm.JvmName("getTimestampMs")
        get() = _builder.timestampMs
      @kotlin.jvm.JvmName("setTimestampMs")
        set(value) {
        _builder.timestampMs = value
      }
    /**
     * `int64 timestamp_ms = 3;`
     */
    public fun clearTimestampMs() {
      _builder.clearTimestampMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.KeyboardTapEvent.copy(block: `com.skymouse.skymouseclient.proto`.KeyboardTapEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.KeyboardTapEvent =
  `com.skymouse.skymouseclient.proto`.KeyboardTapEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

