// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface KeyboardTapEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.KeyboardTapEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.skymouse.KeyboardKey key = 1;</code>
   * @return The enum numeric value on the wire for key.
   */
  int getKeyValue();
  /**
   * <code>.skymouse.KeyboardKey key = 1;</code>
   * @return The key.
   */
  com.skymouse.skymouseclient.proto.KeyboardKey getKey();

  /**
   * <code>.skymouse.ButtonState state = 2;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.skymouse.ButtonState state = 2;</code>
   * @return The state.
   */
  com.skymouse.skymouseclient.proto.ButtonState getState();

  /**
   * <code>int64 timestamp_ms = 3;</code>
   * @return The timestampMs.
   */
  long getTimestampMs();
}
