// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

/**
 * Protobuf enum {@code skymouse.KeyboardKey}
 */
@com.google.protobuf.Generated
public enum KeyboardKey
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>KEY_UNKNOWN = 0;</code>
   */
  KEY_UNKNOWN(0),
  /**
   * <code>KEY_ENTER = 1;</code>
   */
  KEY_ENTER(1),
  /**
   * <code>KEY_BACKSPACE = 2;</code>
   */
  KEY_BACKSPACE(2),
  /**
   * <code>KEY_VOL_DOWN = 3;</code>
   */
  KEY_VOL_DOWN(3),
  /**
   * <code>KEY_VOL_UP = 4;</code>
   */
  KEY_VOL_UP(4),
  /**
   * <code>KEY_VOL_MUTE = 5;</code>
   */
  KEY_VOL_MUTE(5),
  /**
   * <code>KEY_AUDIO_PAUSE = 6;</code>
   */
  KEY_AUDIO_PAUSE(6),
  /**
   * <code>KEY_AUDIO_PREV = 7;</code>
   */
  KEY_AUDIO_PREV(7),
  /**
   * <code>KEY_AUDIO_NEXT = 8;</code>
   */
  KEY_AUDIO_NEXT(8),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "KeyboardKey");
  }
  /**
   * <code>KEY_UNKNOWN = 0;</code>
   */
  public static final int KEY_UNKNOWN_VALUE = 0;
  /**
   * <code>KEY_ENTER = 1;</code>
   */
  public static final int KEY_ENTER_VALUE = 1;
  /**
   * <code>KEY_BACKSPACE = 2;</code>
   */
  public static final int KEY_BACKSPACE_VALUE = 2;
  /**
   * <code>KEY_VOL_DOWN = 3;</code>
   */
  public static final int KEY_VOL_DOWN_VALUE = 3;
  /**
   * <code>KEY_VOL_UP = 4;</code>
   */
  public static final int KEY_VOL_UP_VALUE = 4;
  /**
   * <code>KEY_VOL_MUTE = 5;</code>
   */
  public static final int KEY_VOL_MUTE_VALUE = 5;
  /**
   * <code>KEY_AUDIO_PAUSE = 6;</code>
   */
  public static final int KEY_AUDIO_PAUSE_VALUE = 6;
  /**
   * <code>KEY_AUDIO_PREV = 7;</code>
   */
  public static final int KEY_AUDIO_PREV_VALUE = 7;
  /**
   * <code>KEY_AUDIO_NEXT = 8;</code>
   */
  public static final int KEY_AUDIO_NEXT_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static KeyboardKey valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static KeyboardKey forNumber(int value) {
    switch (value) {
      case 0: return KEY_UNKNOWN;
      case 1: return KEY_ENTER;
      case 2: return KEY_BACKSPACE;
      case 3: return KEY_VOL_DOWN;
      case 4: return KEY_VOL_UP;
      case 5: return KEY_VOL_MUTE;
      case 6: return KEY_AUDIO_PAUSE;
      case 7: return KEY_AUDIO_PREV;
      case 8: return KEY_AUDIO_NEXT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<KeyboardKey>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      KeyboardKey> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<KeyboardKey>() {
          public KeyboardKey findValueByNumber(int number) {
            return KeyboardKey.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.skymouse.skymouseclient.proto.Skymouse.getDescriptor().getEnumType(2);
  }

  private static final KeyboardKey[] VALUES = values();

  public static KeyboardKey valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private KeyboardKey(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:skymouse.KeyboardKey)
}

