// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializemessageToClient")
public inline fun messageToClient(block: com.skymouse.skymouseclient.proto.MessageToClientKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.MessageToClient =
  com.skymouse.skymouseclient.proto.MessageToClientKt.Dsl._create(com.skymouse.skymouseclient.proto.MessageToClient.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.MessageToClient`
 */
public object MessageToClientKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.MessageToClient.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.MessageToClient.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.MessageToClient = _builder.build()

    /**
     * `.skymouse.ServerHello server_hello = 1;`
     */
    public var serverHello: com.skymouse.skymouseclient.proto.ServerHello
      @kotlin.jvm.JvmName("getServerHello")
        get() = _builder.serverHello
      @kotlin.jvm.JvmName("setServerHello")
        set(value) {
        _builder.serverHello = value
      }
    /**
     * `.skymouse.ServerHello server_hello = 1;`
     */
    public fun clearServerHello() {
      _builder.clearServerHello()
    }
    /**
     * `.skymouse.ServerHello server_hello = 1;`
     * @return Whether the serverHello field is set.
     */
    public fun hasServerHello(): kotlin.Boolean {
      return _builder.hasServerHello()
    }
    public val eventCase: com.skymouse.skymouseclient.proto.MessageToClient.EventCase
    @kotlin.jvm.JvmName("getEventCase")
      get() = _builder.getEventCase()

    public fun clearEvent() {
      _builder.clearEvent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.MessageToClient.copy(block: `com.skymouse.skymouseclient.proto`.MessageToClientKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.MessageToClient =
  `com.skymouse.skymouseclient.proto`.MessageToClientKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.skymouse.skymouseclient.proto.MessageToClientOrBuilder.serverHelloOrNull: com.skymouse.skymouseclient.proto.ServerHello?
  get() = if (hasServerHello()) getServerHello() else null

