// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializemessageToServer")
public inline fun messageToServer(block: com.skymouse.skymouseclient.proto.MessageToServerKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.MessageToServer =
  com.skymouse.skymouseclient.proto.MessageToServerKt.Dsl._create(com.skymouse.skymouseclient.proto.MessageToServer.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.MessageToServer`
 */
public object MessageToServerKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.MessageToServer.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.MessageToServer.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.MessageToServer = _builder.build()

    /**
     * `.skymouse.ClientHello client_hello = 1;`
     */
    public var clientHello: com.skymouse.skymouseclient.proto.ClientHello
      @kotlin.jvm.JvmName("getClientHello")
        get() = _builder.clientHello
      @kotlin.jvm.JvmName("setClientHello")
        set(value) {
        _builder.clientHello = value
      }
    /**
     * `.skymouse.ClientHello client_hello = 1;`
     */
    public fun clearClientHello() {
      _builder.clearClientHello()
    }
    /**
     * `.skymouse.ClientHello client_hello = 1;`
     * @return Whether the clientHello field is set.
     */
    public fun hasClientHello(): kotlin.Boolean {
      return _builder.hasClientHello()
    }

    /**
     * `.skymouse.EmulatorEvent emulator_event = 2;`
     */
    public var emulatorEvent: com.skymouse.skymouseclient.proto.EmulatorEvent
      @kotlin.jvm.JvmName("getEmulatorEvent")
        get() = _builder.emulatorEvent
      @kotlin.jvm.JvmName("setEmulatorEvent")
        set(value) {
        _builder.emulatorEvent = value
      }
    /**
     * `.skymouse.EmulatorEvent emulator_event = 2;`
     */
    public fun clearEmulatorEvent() {
      _builder.clearEmulatorEvent()
    }
    /**
     * `.skymouse.EmulatorEvent emulator_event = 2;`
     * @return Whether the emulatorEvent field is set.
     */
    public fun hasEmulatorEvent(): kotlin.Boolean {
      return _builder.hasEmulatorEvent()
    }

    /**
     * `.skymouse.Ping ping = 3;`
     */
    public var ping: com.skymouse.skymouseclient.proto.Ping
      @kotlin.jvm.JvmName("getPing")
        get() = _builder.ping
      @kotlin.jvm.JvmName("setPing")
        set(value) {
        _builder.ping = value
      }
    /**
     * `.skymouse.Ping ping = 3;`
     */
    public fun clearPing() {
      _builder.clearPing()
    }
    /**
     * `.skymouse.Ping ping = 3;`
     * @return Whether the ping field is set.
     */
    public fun hasPing(): kotlin.Boolean {
      return _builder.hasPing()
    }

    /**
     * `.skymouse.Pong pong = 4;`
     */
    public var pong: com.skymouse.skymouseclient.proto.Pong
      @kotlin.jvm.JvmName("getPong")
        get() = _builder.pong
      @kotlin.jvm.JvmName("setPong")
        set(value) {
        _builder.pong = value
      }
    /**
     * `.skymouse.Pong pong = 4;`
     */
    public fun clearPong() {
      _builder.clearPong()
    }
    /**
     * `.skymouse.Pong pong = 4;`
     * @return Whether the pong field is set.
     */
    public fun hasPong(): kotlin.Boolean {
      return _builder.hasPong()
    }

    /**
     * `.skymouse.CommandEvent command = 5;`
     */
    public var command: com.skymouse.skymouseclient.proto.CommandEvent
      @kotlin.jvm.JvmName("getCommand")
        get() = _builder.command
      @kotlin.jvm.JvmName("setCommand")
        set(value) {
        _builder.command = value
      }
    public var commandValue: kotlin.Int
      @kotlin.jvm.JvmName("getCommandValue")
        get() = _builder.commandValue
      @kotlin.jvm.JvmName("setCommandValue")
        set(value) {
        _builder.commandValue = value
      }
    /**
     * `.skymouse.CommandEvent command = 5;`
     */
    public fun clearCommand() {
      _builder.clearCommand()
    }
    /**
     * `.skymouse.CommandEvent command = 5;`
     * @return Whether the command field is set.
     */
    public fun hasCommand(): kotlin.Boolean {
      return _builder.hasCommand()
    }

    /**
     * `.skymouse.ClipboardShareEvent clipboard_share = 6;`
     */
    public var clipboardShare: com.skymouse.skymouseclient.proto.ClipboardShareEvent
      @kotlin.jvm.JvmName("getClipboardShare")
        get() = _builder.clipboardShare
      @kotlin.jvm.JvmName("setClipboardShare")
        set(value) {
        _builder.clipboardShare = value
      }
    /**
     * `.skymouse.ClipboardShareEvent clipboard_share = 6;`
     */
    public fun clearClipboardShare() {
      _builder.clearClipboardShare()
    }
    /**
     * `.skymouse.ClipboardShareEvent clipboard_share = 6;`
     * @return Whether the clipboardShare field is set.
     */
    public fun hasClipboardShare(): kotlin.Boolean {
      return _builder.hasClipboardShare()
    }

    /**
     * `.skymouse.GetCursorScaleEvent get_cursor_scale = 7;`
     */
    public var getCursorScale: com.skymouse.skymouseclient.proto.GetCursorScaleEvent
      @kotlin.jvm.JvmName("getGetCursorScale")
        get() = _builder.getCursorScale
      @kotlin.jvm.JvmName("setGetCursorScale")
        set(value) {
        _builder.getCursorScale = value
      }
    /**
     * `.skymouse.GetCursorScaleEvent get_cursor_scale = 7;`
     */
    public fun clearGetCursorScale() {
      _builder.clearGetCursorScale()
    }
    /**
     * `.skymouse.GetCursorScaleEvent get_cursor_scale = 7;`
     * @return Whether the getCursorScale field is set.
     */
    public fun hasGetCursorScale(): kotlin.Boolean {
      return _builder.hasGetCursorScale()
    }

    /**
     * `.skymouse.SetCursorScaleEvent set_cursor_scale = 8;`
     */
    public var setCursorScale: com.skymouse.skymouseclient.proto.SetCursorScaleEvent
      @kotlin.jvm.JvmName("getSetCursorScale")
        get() = _builder.setCursorScale
      @kotlin.jvm.JvmName("setSetCursorScale")
        set(value) {
        _builder.setCursorScale = value
      }
    /**
     * `.skymouse.SetCursorScaleEvent set_cursor_scale = 8;`
     */
    public fun clearSetCursorScale() {
      _builder.clearSetCursorScale()
    }
    /**
     * `.skymouse.SetCursorScaleEvent set_cursor_scale = 8;`
     * @return Whether the setCursorScale field is set.
     */
    public fun hasSetCursorScale(): kotlin.Boolean {
      return _builder.hasSetCursorScale()
    }

    /**
     * `.skymouse.KeyboardStringEvent keyboard_string_event = 9;`
     */
    public var keyboardStringEvent: com.skymouse.skymouseclient.proto.KeyboardStringEvent
      @kotlin.jvm.JvmName("getKeyboardStringEvent")
        get() = _builder.keyboardStringEvent
      @kotlin.jvm.JvmName("setKeyboardStringEvent")
        set(value) {
        _builder.keyboardStringEvent = value
      }
    /**
     * `.skymouse.KeyboardStringEvent keyboard_string_event = 9;`
     */
    public fun clearKeyboardStringEvent() {
      _builder.clearKeyboardStringEvent()
    }
    /**
     * `.skymouse.KeyboardStringEvent keyboard_string_event = 9;`
     * @return Whether the keyboardStringEvent field is set.
     */
    public fun hasKeyboardStringEvent(): kotlin.Boolean {
      return _builder.hasKeyboardStringEvent()
    }

    /**
     * `.skymouse.KeyboardTapEvent keyboard_tap_event = 10;`
     */
    public var keyboardTapEvent: com.skymouse.skymouseclient.proto.KeyboardTapEvent
      @kotlin.jvm.JvmName("getKeyboardTapEvent")
        get() = _builder.keyboardTapEvent
      @kotlin.jvm.JvmName("setKeyboardTapEvent")
        set(value) {
        _builder.keyboardTapEvent = value
      }
    /**
     * `.skymouse.KeyboardTapEvent keyboard_tap_event = 10;`
     */
    public fun clearKeyboardTapEvent() {
      _builder.clearKeyboardTapEvent()
    }
    /**
     * `.skymouse.KeyboardTapEvent keyboard_tap_event = 10;`
     * @return Whether the keyboardTapEvent field is set.
     */
    public fun hasKeyboardTapEvent(): kotlin.Boolean {
      return _builder.hasKeyboardTapEvent()
    }
    public val eventCase: com.skymouse.skymouseclient.proto.MessageToServer.EventCase
    @kotlin.jvm.JvmName("getEventCase")
      get() = _builder.getEventCase()

    public fun clearEvent() {
      _builder.clearEvent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.MessageToServer.copy(block: `com.skymouse.skymouseclient.proto`.MessageToServerKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.MessageToServer =
  `com.skymouse.skymouseclient.proto`.MessageToServerKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.clientHelloOrNull: com.skymouse.skymouseclient.proto.ClientHello?
  get() = if (hasClientHello()) getClientHello() else null

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.emulatorEventOrNull: com.skymouse.skymouseclient.proto.EmulatorEvent?
  get() = if (hasEmulatorEvent()) getEmulatorEvent() else null

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.pingOrNull: com.skymouse.skymouseclient.proto.Ping?
  get() = if (hasPing()) getPing() else null

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.pongOrNull: com.skymouse.skymouseclient.proto.Pong?
  get() = if (hasPong()) getPong() else null

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.clipboardShareOrNull: com.skymouse.skymouseclient.proto.ClipboardShareEvent?
  get() = if (hasClipboardShare()) getClipboardShare() else null

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.getCursorScaleOrNull: com.skymouse.skymouseclient.proto.GetCursorScaleEvent?
  get() = if (hasGetCursorScale()) getGetCursorScale() else null

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.setCursorScaleOrNull: com.skymouse.skymouseclient.proto.SetCursorScaleEvent?
  get() = if (hasSetCursorScale()) getSetCursorScale() else null

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.keyboardStringEventOrNull: com.skymouse.skymouseclient.proto.KeyboardStringEvent?
  get() = if (hasKeyboardStringEvent()) getKeyboardStringEvent() else null

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.keyboardTapEventOrNull: com.skymouse.skymouseclient.proto.KeyboardTapEvent?
  get() = if (hasKeyboardTapEvent()) getKeyboardTapEvent() else null

