// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializemessageToServer")
public inline fun messageToServer(block: com.skymouse.skymouseclient.proto.MessageToServerKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.MessageToServer =
  com.skymouse.skymouseclient.proto.MessageToServerKt.Dsl._create(com.skymouse.skymouseclient.proto.MessageToServer.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.MessageToServer`
 */
public object MessageToServerKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.MessageToServer.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.MessageToServer.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.MessageToServer = _builder.build()

    /**
     * `.skymouse.MouseEvent mouse = 1;`
     */
    public var mouse: com.skymouse.skymouseclient.proto.MouseEvent
      @kotlin.jvm.JvmName("getMouse")
        get() = _builder.mouse
      @kotlin.jvm.JvmName("setMouse")
        set(value) {
        _builder.mouse = value
      }
    /**
     * `.skymouse.MouseEvent mouse = 1;`
     */
    public fun clearMouse() {
      _builder.clearMouse()
    }
    /**
     * `.skymouse.MouseEvent mouse = 1;`
     * @return Whether the mouse field is set.
     */
    public fun hasMouse(): kotlin.Boolean {
      return _builder.hasMouse()
    }

    /**
     * `.skymouse.ClickEvent click = 2;`
     */
    public var click: com.skymouse.skymouseclient.proto.ClickEvent
      @kotlin.jvm.JvmName("getClick")
        get() = _builder.click
      @kotlin.jvm.JvmName("setClick")
        set(value) {
        _builder.click = value
      }
    /**
     * `.skymouse.ClickEvent click = 2;`
     */
    public fun clearClick() {
      _builder.clearClick()
    }
    /**
     * `.skymouse.ClickEvent click = 2;`
     * @return Whether the click field is set.
     */
    public fun hasClick(): kotlin.Boolean {
      return _builder.hasClick()
    }

    /**
     * `.skymouse.ScrollEvent scroll = 3;`
     */
    public var scroll: com.skymouse.skymouseclient.proto.ScrollEvent
      @kotlin.jvm.JvmName("getScroll")
        get() = _builder.scroll
      @kotlin.jvm.JvmName("setScroll")
        set(value) {
        _builder.scroll = value
      }
    /**
     * `.skymouse.ScrollEvent scroll = 3;`
     */
    public fun clearScroll() {
      _builder.clearScroll()
    }
    /**
     * `.skymouse.ScrollEvent scroll = 3;`
     * @return Whether the scroll field is set.
     */
    public fun hasScroll(): kotlin.Boolean {
      return _builder.hasScroll()
    }
    public val eventCase: com.skymouse.skymouseclient.proto.MessageToServer.EventCase
    @kotlin.jvm.JvmName("getEventCase")
      get() = _builder.getEventCase()

    public fun clearEvent() {
      _builder.clearEvent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.MessageToServer.copy(block: `com.skymouse.skymouseclient.proto`.MessageToServerKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.MessageToServer =
  `com.skymouse.skymouseclient.proto`.MessageToServerKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.mouseOrNull: com.skymouse.skymouseclient.proto.MouseEvent?
  get() = if (hasMouse()) getMouse() else null

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.clickOrNull: com.skymouse.skymouseclient.proto.ClickEvent?
  get() = if (hasClick()) getClick() else null

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.scrollOrNull: com.skymouse.skymouseclient.proto.ScrollEvent?
  get() = if (hasScroll()) getScroll() else null

