// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface MessageToServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.MessageToServer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.skymouse.ClientHello client_hello = 1;</code>
   * @return Whether the clientHello field is set.
   */
  boolean hasClientHello();
  /**
   * <code>.skymouse.ClientHello client_hello = 1;</code>
   * @return The clientHello.
   */
  com.skymouse.skymouseclient.proto.ClientHello getClientHello();
  /**
   * <code>.skymouse.ClientHello client_hello = 1;</code>
   */
  com.skymouse.skymouseclient.proto.ClientHelloOrBuilder getClientHelloOrBuilder();

  /**
   * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
   * @return Whether the emulatorEvent field is set.
   */
  boolean hasEmulatorEvent();
  /**
   * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
   * @return The emulatorEvent.
   */
  com.skymouse.skymouseclient.proto.EmulatorEvent getEmulatorEvent();
  /**
   * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
   */
  com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder getEmulatorEventOrBuilder();

  /**
   * <code>.skymouse.Ping ping = 3;</code>
   * @return Whether the ping field is set.
   */
  boolean hasPing();
  /**
   * <code>.skymouse.Ping ping = 3;</code>
   * @return The ping.
   */
  com.skymouse.skymouseclient.proto.Ping getPing();
  /**
   * <code>.skymouse.Ping ping = 3;</code>
   */
  com.skymouse.skymouseclient.proto.PingOrBuilder getPingOrBuilder();

  /**
   * <code>.skymouse.Pong pong = 4;</code>
   * @return Whether the pong field is set.
   */
  boolean hasPong();
  /**
   * <code>.skymouse.Pong pong = 4;</code>
   * @return The pong.
   */
  com.skymouse.skymouseclient.proto.Pong getPong();
  /**
   * <code>.skymouse.Pong pong = 4;</code>
   */
  com.skymouse.skymouseclient.proto.PongOrBuilder getPongOrBuilder();

  /**
   * <code>.skymouse.CommandEvent command = 5;</code>
   * @return Whether the command field is set.
   */
  boolean hasCommand();
  /**
   * <code>.skymouse.CommandEvent command = 5;</code>
   * @return The enum numeric value on the wire for command.
   */
  int getCommandValue();
  /**
   * <code>.skymouse.CommandEvent command = 5;</code>
   * @return The command.
   */
  com.skymouse.skymouseclient.proto.CommandEvent getCommand();

  /**
   * <code>.skymouse.ClipboardShareEvent clipboard_share = 6;</code>
   * @return Whether the clipboardShare field is set.
   */
  boolean hasClipboardShare();
  /**
   * <code>.skymouse.ClipboardShareEvent clipboard_share = 6;</code>
   * @return The clipboardShare.
   */
  com.skymouse.skymouseclient.proto.ClipboardShareEvent getClipboardShare();
  /**
   * <code>.skymouse.ClipboardShareEvent clipboard_share = 6;</code>
   */
  com.skymouse.skymouseclient.proto.ClipboardShareEventOrBuilder getClipboardShareOrBuilder();

  /**
   * <code>.skymouse.GetCursorScaleEvent get_cursor_scale = 7;</code>
   * @return Whether the getCursorScale field is set.
   */
  boolean hasGetCursorScale();
  /**
   * <code>.skymouse.GetCursorScaleEvent get_cursor_scale = 7;</code>
   * @return The getCursorScale.
   */
  com.skymouse.skymouseclient.proto.GetCursorScaleEvent getGetCursorScale();
  /**
   * <code>.skymouse.GetCursorScaleEvent get_cursor_scale = 7;</code>
   */
  com.skymouse.skymouseclient.proto.GetCursorScaleEventOrBuilder getGetCursorScaleOrBuilder();

  /**
   * <code>.skymouse.SetCursorScaleEvent set_cursor_scale = 8;</code>
   * @return Whether the setCursorScale field is set.
   */
  boolean hasSetCursorScale();
  /**
   * <code>.skymouse.SetCursorScaleEvent set_cursor_scale = 8;</code>
   * @return The setCursorScale.
   */
  com.skymouse.skymouseclient.proto.SetCursorScaleEvent getSetCursorScale();
  /**
   * <code>.skymouse.SetCursorScaleEvent set_cursor_scale = 8;</code>
   */
  com.skymouse.skymouseclient.proto.SetCursorScaleEventOrBuilder getSetCursorScaleOrBuilder();

  /**
   * <code>.skymouse.KeyboardStringEvent keyboard_string_event = 9;</code>
   * @return Whether the keyboardStringEvent field is set.
   */
  boolean hasKeyboardStringEvent();
  /**
   * <code>.skymouse.KeyboardStringEvent keyboard_string_event = 9;</code>
   * @return The keyboardStringEvent.
   */
  com.skymouse.skymouseclient.proto.KeyboardStringEvent getKeyboardStringEvent();
  /**
   * <code>.skymouse.KeyboardStringEvent keyboard_string_event = 9;</code>
   */
  com.skymouse.skymouseclient.proto.KeyboardStringEventOrBuilder getKeyboardStringEventOrBuilder();

  /**
   * <code>.skymouse.KeyboardTapEvent keyboard_tap_event = 10;</code>
   * @return Whether the keyboardTapEvent field is set.
   */
  boolean hasKeyboardTapEvent();
  /**
   * <code>.skymouse.KeyboardTapEvent keyboard_tap_event = 10;</code>
   * @return The keyboardTapEvent.
   */
  com.skymouse.skymouseclient.proto.KeyboardTapEvent getKeyboardTapEvent();
  /**
   * <code>.skymouse.KeyboardTapEvent keyboard_tap_event = 10;</code>
   */
  com.skymouse.skymouseclient.proto.KeyboardTapEventOrBuilder getKeyboardTapEventOrBuilder();

  com.skymouse.skymouseclient.proto.MessageToServer.EventCase getEventCase();
}
