// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface MessageToClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.MessageToClient)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.skymouse.ServerHello server_hello = 1;</code>
   * @return Whether the serverHello field is set.
   */
  boolean hasServerHello();
  /**
   * <code>.skymouse.ServerHello server_hello = 1;</code>
   * @return The serverHello.
   */
  com.skymouse.skymouseclient.proto.ServerHello getServerHello();
  /**
   * <code>.skymouse.ServerHello server_hello = 1;</code>
   */
  com.skymouse.skymouseclient.proto.ServerHelloOrBuilder getServerHelloOrBuilder();

  /**
   * <code>.skymouse.ServerEvent server_event = 2;</code>
   * @return Whether the serverEvent field is set.
   */
  boolean hasServerEvent();
  /**
   * <code>.skymouse.ServerEvent server_event = 2;</code>
   * @return The serverEvent.
   */
  com.skymouse.skymouseclient.proto.ServerEvent getServerEvent();
  /**
   * <code>.skymouse.ServerEvent server_event = 2;</code>
   */
  com.skymouse.skymouseclient.proto.ServerEventOrBuilder getServerEventOrBuilder();

  /**
   * <code>.skymouse.Pong pong = 3;</code>
   * @return Whether the pong field is set.
   */
  boolean hasPong();
  /**
   * <code>.skymouse.Pong pong = 3;</code>
   * @return The pong.
   */
  com.skymouse.skymouseclient.proto.Pong getPong();
  /**
   * <code>.skymouse.Pong pong = 3;</code>
   */
  com.skymouse.skymouseclient.proto.PongOrBuilder getPongOrBuilder();

  /**
   * <code>.skymouse.CurrentCursorScaleAnswer current_cursor_scale_answer = 4;</code>
   * @return Whether the currentCursorScaleAnswer field is set.
   */
  boolean hasCurrentCursorScaleAnswer();
  /**
   * <code>.skymouse.CurrentCursorScaleAnswer current_cursor_scale_answer = 4;</code>
   * @return The currentCursorScaleAnswer.
   */
  com.skymouse.skymouseclient.proto.CurrentCursorScaleAnswer getCurrentCursorScaleAnswer();
  /**
   * <code>.skymouse.CurrentCursorScaleAnswer current_cursor_scale_answer = 4;</code>
   */
  com.skymouse.skymouseclient.proto.CurrentCursorScaleAnswerOrBuilder getCurrentCursorScaleAnswerOrBuilder();

  com.skymouse.skymouseclient.proto.MessageToClient.EventCase getEventCase();
}
