// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

/**
 * Protobuf type {@code skymouse.MessageToClient}
 */
@com.google.protobuf.Generated
public final class MessageToClient extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:skymouse.MessageToClient)
    MessageToClientOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "MessageToClient");
  }
  // Use MessageToClient.newBuilder() to construct.
  private MessageToClient(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MessageToClient() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_MessageToClient_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_MessageToClient_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_MessageToClient_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.skymouse.skymouseclient.proto.MessageToClient.class, com.skymouse.skymouseclient.proto.MessageToClient.Builder.class);
  }

  private int eventCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object event_;
  public enum EventCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SERVER_HELLO(1),
    SERVER_EVENT(2),
    EVENT_NOT_SET(0);
    private final int value;
    private EventCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventCase forNumber(int value) {
      switch (value) {
        case 1: return SERVER_HELLO;
        case 2: return SERVER_EVENT;
        case 0: return EVENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EventCase
  getEventCase() {
    return EventCase.forNumber(
        eventCase_);
  }

  public static final int SERVER_HELLO_FIELD_NUMBER = 1;
  /**
   * <code>.skymouse.ServerHello server_hello = 1;</code>
   * @return Whether the serverHello field is set.
   */
  @java.lang.Override
  public boolean hasServerHello() {
    return eventCase_ == 1;
  }
  /**
   * <code>.skymouse.ServerHello server_hello = 1;</code>
   * @return The serverHello.
   */
  @java.lang.Override
  public com.skymouse.skymouseclient.proto.ServerHello getServerHello() {
    if (eventCase_ == 1) {
       return (com.skymouse.skymouseclient.proto.ServerHello) event_;
    }
    return com.skymouse.skymouseclient.proto.ServerHello.getDefaultInstance();
  }
  /**
   * <code>.skymouse.ServerHello server_hello = 1;</code>
   */
  @java.lang.Override
  public com.skymouse.skymouseclient.proto.ServerHelloOrBuilder getServerHelloOrBuilder() {
    if (eventCase_ == 1) {
       return (com.skymouse.skymouseclient.proto.ServerHello) event_;
    }
    return com.skymouse.skymouseclient.proto.ServerHello.getDefaultInstance();
  }

  public static final int SERVER_EVENT_FIELD_NUMBER = 2;
  /**
   * <code>.skymouse.ServerEvent server_event = 2;</code>
   * @return Whether the serverEvent field is set.
   */
  @java.lang.Override
  public boolean hasServerEvent() {
    return eventCase_ == 2;
  }
  /**
   * <code>.skymouse.ServerEvent server_event = 2;</code>
   * @return The serverEvent.
   */
  @java.lang.Override
  public com.skymouse.skymouseclient.proto.ServerEvent getServerEvent() {
    if (eventCase_ == 2) {
       return (com.skymouse.skymouseclient.proto.ServerEvent) event_;
    }
    return com.skymouse.skymouseclient.proto.ServerEvent.getDefaultInstance();
  }
  /**
   * <code>.skymouse.ServerEvent server_event = 2;</code>
   */
  @java.lang.Override
  public com.skymouse.skymouseclient.proto.ServerEventOrBuilder getServerEventOrBuilder() {
    if (eventCase_ == 2) {
       return (com.skymouse.skymouseclient.proto.ServerEvent) event_;
    }
    return com.skymouse.skymouseclient.proto.ServerEvent.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventCase_ == 1) {
      output.writeMessage(1, (com.skymouse.skymouseclient.proto.ServerHello) event_);
    }
    if (eventCase_ == 2) {
      output.writeMessage(2, (com.skymouse.skymouseclient.proto.ServerEvent) event_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (eventCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.skymouse.skymouseclient.proto.ServerHello) event_);
    }
    if (eventCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.skymouse.skymouseclient.proto.ServerEvent) event_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.skymouse.skymouseclient.proto.MessageToClient)) {
      return super.equals(obj);
    }
    com.skymouse.skymouseclient.proto.MessageToClient other = (com.skymouse.skymouseclient.proto.MessageToClient) obj;

    if (!getEventCase().equals(other.getEventCase())) return false;
    switch (eventCase_) {
      case 1:
        if (!getServerHello()
            .equals(other.getServerHello())) return false;
        break;
      case 2:
        if (!getServerEvent()
            .equals(other.getServerEvent())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (eventCase_) {
      case 1:
        hash = (37 * hash) + SERVER_HELLO_FIELD_NUMBER;
        hash = (53 * hash) + getServerHello().hashCode();
        break;
      case 2:
        hash = (37 * hash) + SERVER_EVENT_FIELD_NUMBER;
        hash = (53 * hash) + getServerEvent().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.skymouse.skymouseclient.proto.MessageToClient parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.MessageToClient parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.MessageToClient parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.MessageToClient parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.MessageToClient parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.MessageToClient parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.MessageToClient parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.skymouse.skymouseclient.proto.MessageToClient parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.skymouse.skymouseclient.proto.MessageToClient parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.skymouse.skymouseclient.proto.MessageToClient parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.MessageToClient parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.skymouse.skymouseclient.proto.MessageToClient parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.skymouse.skymouseclient.proto.MessageToClient prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code skymouse.MessageToClient}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:skymouse.MessageToClient)
      com.skymouse.skymouseclient.proto.MessageToClientOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_MessageToClient_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_MessageToClient_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skymouse.skymouseclient.proto.MessageToClient.class, com.skymouse.skymouseclient.proto.MessageToClient.Builder.class);
    }

    // Construct using com.skymouse.skymouseclient.proto.MessageToClient.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (serverHelloBuilder_ != null) {
        serverHelloBuilder_.clear();
      }
      if (serverEventBuilder_ != null) {
        serverEventBuilder_.clear();
      }
      eventCase_ = 0;
      event_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_MessageToClient_descriptor;
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.MessageToClient getDefaultInstanceForType() {
      return com.skymouse.skymouseclient.proto.MessageToClient.getDefaultInstance();
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.MessageToClient build() {
      com.skymouse.skymouseclient.proto.MessageToClient result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.MessageToClient buildPartial() {
      com.skymouse.skymouseclient.proto.MessageToClient result = new com.skymouse.skymouseclient.proto.MessageToClient(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.skymouse.skymouseclient.proto.MessageToClient result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.skymouse.skymouseclient.proto.MessageToClient result) {
      result.eventCase_ = eventCase_;
      result.event_ = this.event_;
      if (eventCase_ == 1 &&
          serverHelloBuilder_ != null) {
        result.event_ = serverHelloBuilder_.build();
      }
      if (eventCase_ == 2 &&
          serverEventBuilder_ != null) {
        result.event_ = serverEventBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.skymouse.skymouseclient.proto.MessageToClient) {
        return mergeFrom((com.skymouse.skymouseclient.proto.MessageToClient)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.skymouse.skymouseclient.proto.MessageToClient other) {
      if (other == com.skymouse.skymouseclient.proto.MessageToClient.getDefaultInstance()) return this;
      switch (other.getEventCase()) {
        case SERVER_HELLO: {
          mergeServerHello(other.getServerHello());
          break;
        }
        case SERVER_EVENT: {
          mergeServerEvent(other.getServerEvent());
          break;
        }
        case EVENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetServerHelloFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetServerEventFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int eventCase_ = 0;
    private java.lang.Object event_;
    public EventCase
        getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public Builder clearEvent() {
      eventCase_ = 0;
      event_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.skymouse.skymouseclient.proto.ServerHello, com.skymouse.skymouseclient.proto.ServerHello.Builder, com.skymouse.skymouseclient.proto.ServerHelloOrBuilder> serverHelloBuilder_;
    /**
     * <code>.skymouse.ServerHello server_hello = 1;</code>
     * @return Whether the serverHello field is set.
     */
    @java.lang.Override
    public boolean hasServerHello() {
      return eventCase_ == 1;
    }
    /**
     * <code>.skymouse.ServerHello server_hello = 1;</code>
     * @return The serverHello.
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ServerHello getServerHello() {
      if (serverHelloBuilder_ == null) {
        if (eventCase_ == 1) {
          return (com.skymouse.skymouseclient.proto.ServerHello) event_;
        }
        return com.skymouse.skymouseclient.proto.ServerHello.getDefaultInstance();
      } else {
        if (eventCase_ == 1) {
          return serverHelloBuilder_.getMessage();
        }
        return com.skymouse.skymouseclient.proto.ServerHello.getDefaultInstance();
      }
    }
    /**
     * <code>.skymouse.ServerHello server_hello = 1;</code>
     */
    public Builder setServerHello(com.skymouse.skymouseclient.proto.ServerHello value) {
      if (serverHelloBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        serverHelloBuilder_.setMessage(value);
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.skymouse.ServerHello server_hello = 1;</code>
     */
    public Builder setServerHello(
        com.skymouse.skymouseclient.proto.ServerHello.Builder builderForValue) {
      if (serverHelloBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        serverHelloBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.skymouse.ServerHello server_hello = 1;</code>
     */
    public Builder mergeServerHello(com.skymouse.skymouseclient.proto.ServerHello value) {
      if (serverHelloBuilder_ == null) {
        if (eventCase_ == 1 &&
            event_ != com.skymouse.skymouseclient.proto.ServerHello.getDefaultInstance()) {
          event_ = com.skymouse.skymouseclient.proto.ServerHello.newBuilder((com.skymouse.skymouseclient.proto.ServerHello) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 1) {
          serverHelloBuilder_.mergeFrom(value);
        } else {
          serverHelloBuilder_.setMessage(value);
        }
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.skymouse.ServerHello server_hello = 1;</code>
     */
    public Builder clearServerHello() {
      if (serverHelloBuilder_ == null) {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
        }
        serverHelloBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.skymouse.ServerHello server_hello = 1;</code>
     */
    public com.skymouse.skymouseclient.proto.ServerHello.Builder getServerHelloBuilder() {
      return internalGetServerHelloFieldBuilder().getBuilder();
    }
    /**
     * <code>.skymouse.ServerHello server_hello = 1;</code>
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ServerHelloOrBuilder getServerHelloOrBuilder() {
      if ((eventCase_ == 1) && (serverHelloBuilder_ != null)) {
        return serverHelloBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 1) {
          return (com.skymouse.skymouseclient.proto.ServerHello) event_;
        }
        return com.skymouse.skymouseclient.proto.ServerHello.getDefaultInstance();
      }
    }
    /**
     * <code>.skymouse.ServerHello server_hello = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.skymouse.skymouseclient.proto.ServerHello, com.skymouse.skymouseclient.proto.ServerHello.Builder, com.skymouse.skymouseclient.proto.ServerHelloOrBuilder> 
        internalGetServerHelloFieldBuilder() {
      if (serverHelloBuilder_ == null) {
        if (!(eventCase_ == 1)) {
          event_ = com.skymouse.skymouseclient.proto.ServerHello.getDefaultInstance();
        }
        serverHelloBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.skymouse.skymouseclient.proto.ServerHello, com.skymouse.skymouseclient.proto.ServerHello.Builder, com.skymouse.skymouseclient.proto.ServerHelloOrBuilder>(
                (com.skymouse.skymouseclient.proto.ServerHello) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 1;
      onChanged();
      return serverHelloBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.skymouse.skymouseclient.proto.ServerEvent, com.skymouse.skymouseclient.proto.ServerEvent.Builder, com.skymouse.skymouseclient.proto.ServerEventOrBuilder> serverEventBuilder_;
    /**
     * <code>.skymouse.ServerEvent server_event = 2;</code>
     * @return Whether the serverEvent field is set.
     */
    @java.lang.Override
    public boolean hasServerEvent() {
      return eventCase_ == 2;
    }
    /**
     * <code>.skymouse.ServerEvent server_event = 2;</code>
     * @return The serverEvent.
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ServerEvent getServerEvent() {
      if (serverEventBuilder_ == null) {
        if (eventCase_ == 2) {
          return (com.skymouse.skymouseclient.proto.ServerEvent) event_;
        }
        return com.skymouse.skymouseclient.proto.ServerEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 2) {
          return serverEventBuilder_.getMessage();
        }
        return com.skymouse.skymouseclient.proto.ServerEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.skymouse.ServerEvent server_event = 2;</code>
     */
    public Builder setServerEvent(com.skymouse.skymouseclient.proto.ServerEvent value) {
      if (serverEventBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        serverEventBuilder_.setMessage(value);
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.skymouse.ServerEvent server_event = 2;</code>
     */
    public Builder setServerEvent(
        com.skymouse.skymouseclient.proto.ServerEvent.Builder builderForValue) {
      if (serverEventBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        serverEventBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.skymouse.ServerEvent server_event = 2;</code>
     */
    public Builder mergeServerEvent(com.skymouse.skymouseclient.proto.ServerEvent value) {
      if (serverEventBuilder_ == null) {
        if (eventCase_ == 2 &&
            event_ != com.skymouse.skymouseclient.proto.ServerEvent.getDefaultInstance()) {
          event_ = com.skymouse.skymouseclient.proto.ServerEvent.newBuilder((com.skymouse.skymouseclient.proto.ServerEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 2) {
          serverEventBuilder_.mergeFrom(value);
        } else {
          serverEventBuilder_.setMessage(value);
        }
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.skymouse.ServerEvent server_event = 2;</code>
     */
    public Builder clearServerEvent() {
      if (serverEventBuilder_ == null) {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
        }
        serverEventBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.skymouse.ServerEvent server_event = 2;</code>
     */
    public com.skymouse.skymouseclient.proto.ServerEvent.Builder getServerEventBuilder() {
      return internalGetServerEventFieldBuilder().getBuilder();
    }
    /**
     * <code>.skymouse.ServerEvent server_event = 2;</code>
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ServerEventOrBuilder getServerEventOrBuilder() {
      if ((eventCase_ == 2) && (serverEventBuilder_ != null)) {
        return serverEventBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 2) {
          return (com.skymouse.skymouseclient.proto.ServerEvent) event_;
        }
        return com.skymouse.skymouseclient.proto.ServerEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.skymouse.ServerEvent server_event = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.skymouse.skymouseclient.proto.ServerEvent, com.skymouse.skymouseclient.proto.ServerEvent.Builder, com.skymouse.skymouseclient.proto.ServerEventOrBuilder> 
        internalGetServerEventFieldBuilder() {
      if (serverEventBuilder_ == null) {
        if (!(eventCase_ == 2)) {
          event_ = com.skymouse.skymouseclient.proto.ServerEvent.getDefaultInstance();
        }
        serverEventBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.skymouse.skymouseclient.proto.ServerEvent, com.skymouse.skymouseclient.proto.ServerEvent.Builder, com.skymouse.skymouseclient.proto.ServerEventOrBuilder>(
                (com.skymouse.skymouseclient.proto.ServerEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 2;
      onChanged();
      return serverEventBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:skymouse.MessageToClient)
  }

  // @@protoc_insertion_point(class_scope:skymouse.MessageToClient)
  private static final com.skymouse.skymouseclient.proto.MessageToClient DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.skymouse.skymouseclient.proto.MessageToClient();
  }

  public static com.skymouse.skymouseclient.proto.MessageToClient getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageToClient>
      PARSER = new com.google.protobuf.AbstractParser<MessageToClient>() {
    @java.lang.Override
    public MessageToClient parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MessageToClient> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageToClient> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.skymouse.skymouseclient.proto.MessageToClient getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

