// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializemessageToServer")
public inline fun messageToServer(block: com.skymouse.skymouseclient.proto.MessageToServerKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.MessageToServer =
  com.skymouse.skymouseclient.proto.MessageToServerKt.Dsl._create(com.skymouse.skymouseclient.proto.MessageToServer.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.MessageToServer`
 */
public object MessageToServerKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.MessageToServer.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.MessageToServer.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.MessageToServer = _builder.build()

    /**
     * `.skymouse.ClientHello client_hello = 1;`
     */
    public var clientHello: com.skymouse.skymouseclient.proto.ClientHello
      @kotlin.jvm.JvmName("getClientHello")
        get() = _builder.clientHello
      @kotlin.jvm.JvmName("setClientHello")
        set(value) {
        _builder.clientHello = value
      }
    /**
     * `.skymouse.ClientHello client_hello = 1;`
     */
    public fun clearClientHello() {
      _builder.clearClientHello()
    }
    /**
     * `.skymouse.ClientHello client_hello = 1;`
     * @return Whether the clientHello field is set.
     */
    public fun hasClientHello(): kotlin.Boolean {
      return _builder.hasClientHello()
    }

    /**
     * `.skymouse.EmulatorEvent emulator_event = 2;`
     */
    public var emulatorEvent: com.skymouse.skymouseclient.proto.EmulatorEvent
      @kotlin.jvm.JvmName("getEmulatorEvent")
        get() = _builder.emulatorEvent
      @kotlin.jvm.JvmName("setEmulatorEvent")
        set(value) {
        _builder.emulatorEvent = value
      }
    /**
     * `.skymouse.EmulatorEvent emulator_event = 2;`
     */
    public fun clearEmulatorEvent() {
      _builder.clearEmulatorEvent()
    }
    /**
     * `.skymouse.EmulatorEvent emulator_event = 2;`
     * @return Whether the emulatorEvent field is set.
     */
    public fun hasEmulatorEvent(): kotlin.Boolean {
      return _builder.hasEmulatorEvent()
    }

    /**
     * `.skymouse.Ping ping = 3;`
     */
    public var ping: com.skymouse.skymouseclient.proto.Ping
      @kotlin.jvm.JvmName("getPing")
        get() = _builder.ping
      @kotlin.jvm.JvmName("setPing")
        set(value) {
        _builder.ping = value
      }
    /**
     * `.skymouse.Ping ping = 3;`
     */
    public fun clearPing() {
      _builder.clearPing()
    }
    /**
     * `.skymouse.Ping ping = 3;`
     * @return Whether the ping field is set.
     */
    public fun hasPing(): kotlin.Boolean {
      return _builder.hasPing()
    }

    /**
     * `.skymouse.Pong pong = 4;`
     */
    public var pong: com.skymouse.skymouseclient.proto.Pong
      @kotlin.jvm.JvmName("getPong")
        get() = _builder.pong
      @kotlin.jvm.JvmName("setPong")
        set(value) {
        _builder.pong = value
      }
    /**
     * `.skymouse.Pong pong = 4;`
     */
    public fun clearPong() {
      _builder.clearPong()
    }
    /**
     * `.skymouse.Pong pong = 4;`
     * @return Whether the pong field is set.
     */
    public fun hasPong(): kotlin.Boolean {
      return _builder.hasPong()
    }
    public val eventCase: com.skymouse.skymouseclient.proto.MessageToServer.EventCase
    @kotlin.jvm.JvmName("getEventCase")
      get() = _builder.getEventCase()

    public fun clearEvent() {
      _builder.clearEvent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.MessageToServer.copy(block: `com.skymouse.skymouseclient.proto`.MessageToServerKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.MessageToServer =
  `com.skymouse.skymouseclient.proto`.MessageToServerKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.clientHelloOrNull: com.skymouse.skymouseclient.proto.ClientHello?
  get() = if (hasClientHello()) getClientHello() else null

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.emulatorEventOrNull: com.skymouse.skymouseclient.proto.EmulatorEvent?
  get() = if (hasEmulatorEvent()) getEmulatorEvent() else null

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.pingOrNull: com.skymouse.skymouseclient.proto.Ping?
  get() = if (hasPing()) getPing() else null

public val com.skymouse.skymouseclient.proto.MessageToServerOrBuilder.pongOrNull: com.skymouse.skymouseclient.proto.Pong?
  get() = if (hasPong()) getPong() else null

