// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface MessageToServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.MessageToServer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.skymouse.ClientHello client_hello = 1;</code>
   * @return Whether the clientHello field is set.
   */
  boolean hasClientHello();
  /**
   * <code>.skymouse.ClientHello client_hello = 1;</code>
   * @return The clientHello.
   */
  com.skymouse.skymouseclient.proto.ClientHello getClientHello();
  /**
   * <code>.skymouse.ClientHello client_hello = 1;</code>
   */
  com.skymouse.skymouseclient.proto.ClientHelloOrBuilder getClientHelloOrBuilder();

  /**
   * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
   * @return Whether the emulatorEvent field is set.
   */
  boolean hasEmulatorEvent();
  /**
   * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
   * @return The emulatorEvent.
   */
  com.skymouse.skymouseclient.proto.EmulatorEvent getEmulatorEvent();
  /**
   * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
   */
  com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder getEmulatorEventOrBuilder();

  /**
   * <code>.skymouse.Ping ping = 3;</code>
   * @return Whether the ping field is set.
   */
  boolean hasPing();
  /**
   * <code>.skymouse.Ping ping = 3;</code>
   * @return The ping.
   */
  com.skymouse.skymouseclient.proto.Ping getPing();
  /**
   * <code>.skymouse.Ping ping = 3;</code>
   */
  com.skymouse.skymouseclient.proto.PingOrBuilder getPingOrBuilder();

  /**
   * <code>.skymouse.Pong pong = 4;</code>
   * @return Whether the pong field is set.
   */
  boolean hasPong();
  /**
   * <code>.skymouse.Pong pong = 4;</code>
   * @return The pong.
   */
  com.skymouse.skymouseclient.proto.Pong getPong();
  /**
   * <code>.skymouse.Pong pong = 4;</code>
   */
  com.skymouse.skymouseclient.proto.PongOrBuilder getPongOrBuilder();

  com.skymouse.skymouseclient.proto.MessageToServer.EventCase getEventCase();
}
