// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

/**
 * Protobuf enum {@code skymouse.MouseButton}
 */
@com.google.protobuf.Generated
public enum MouseButton
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>BUTTON_UNKNOWN = 0;</code>
   */
  BUTTON_UNKNOWN(0),
  /**
   * <code>BUTTON_LEFT = 1;</code>
   */
  BUTTON_LEFT(1),
  /**
   * <code>BUTTON_RIGHT = 2;</code>
   */
  BUTTON_RIGHT(2),
  /**
   * <code>BUTTON_MIDDLE = 3;</code>
   */
  BUTTON_MIDDLE(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "MouseButton");
  }
  /**
   * <code>BUTTON_UNKNOWN = 0;</code>
   */
  public static final int BUTTON_UNKNOWN_VALUE = 0;
  /**
   * <code>BUTTON_LEFT = 1;</code>
   */
  public static final int BUTTON_LEFT_VALUE = 1;
  /**
   * <code>BUTTON_RIGHT = 2;</code>
   */
  public static final int BUTTON_RIGHT_VALUE = 2;
  /**
   * <code>BUTTON_MIDDLE = 3;</code>
   */
  public static final int BUTTON_MIDDLE_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MouseButton valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MouseButton forNumber(int value) {
    switch (value) {
      case 0: return BUTTON_UNKNOWN;
      case 1: return BUTTON_LEFT;
      case 2: return BUTTON_RIGHT;
      case 3: return BUTTON_MIDDLE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MouseButton>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MouseButton> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MouseButton>() {
          public MouseButton findValueByNumber(int number) {
            return MouseButton.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.skymouse.skymouseclient.proto.Skymouse.getDescriptor().getEnumType(0);
  }

  private static final MouseButton[] VALUES = values();

  public static MouseButton valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MouseButton(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:skymouse.MouseButton)
}

