// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

/**
 * Protobuf type {@code skymouse.MouseEvent}
 */
@com.google.protobuf.Generated
public final class MouseEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:skymouse.MouseEvent)
    MouseEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "MouseEvent");
  }
  // Use MouseEvent.newBuilder() to construct.
  private MouseEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MouseEvent() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_MouseEvent_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_MouseEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_MouseEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.skymouse.skymouseclient.proto.MouseEvent.class, com.skymouse.skymouseclient.proto.MouseEvent.Builder.class);
  }

  public static final int DELTA_X_FIELD_NUMBER = 1;
  private float deltaX_ = 0F;
  /**
   * <code>float delta_x = 1;</code>
   * @return The deltaX.
   */
  @java.lang.Override
  public float getDeltaX() {
    return deltaX_;
  }

  public static final int DELTA_Y_FIELD_NUMBER = 2;
  private float deltaY_ = 0F;
  /**
   * <code>float delta_y = 2;</code>
   * @return The deltaY.
   */
  @java.lang.Override
  public float getDeltaY() {
    return deltaY_;
  }

  public static final int TIMESTAMP_MS_FIELD_NUMBER = 3;
  private long timestampMs_ = 0L;
  /**
   * <code>int64 timestamp_ms = 3;</code>
   * @return The timestampMs.
   */
  @java.lang.Override
  public long getTimestampMs() {
    return timestampMs_;
  }

  public static final int SEQUENCE_ID_FIELD_NUMBER = 4;
  private int sequenceId_ = 0;
  /**
   * <code>uint32 sequence_id = 4;</code>
   * @return The sequenceId.
   */
  @java.lang.Override
  public int getSequenceId() {
    return sequenceId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Float.floatToRawIntBits(deltaX_) != 0) {
      output.writeFloat(1, deltaX_);
    }
    if (java.lang.Float.floatToRawIntBits(deltaY_) != 0) {
      output.writeFloat(2, deltaY_);
    }
    if (timestampMs_ != 0L) {
      output.writeInt64(3, timestampMs_);
    }
    if (sequenceId_ != 0) {
      output.writeUInt32(4, sequenceId_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (java.lang.Float.floatToRawIntBits(deltaX_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, deltaX_);
    }
    if (java.lang.Float.floatToRawIntBits(deltaY_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, deltaY_);
    }
    if (timestampMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, timestampMs_);
    }
    if (sequenceId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, sequenceId_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.skymouse.skymouseclient.proto.MouseEvent)) {
      return super.equals(obj);
    }
    com.skymouse.skymouseclient.proto.MouseEvent other = (com.skymouse.skymouseclient.proto.MouseEvent) obj;

    if (java.lang.Float.floatToIntBits(getDeltaX())
        != java.lang.Float.floatToIntBits(
            other.getDeltaX())) return false;
    if (java.lang.Float.floatToIntBits(getDeltaY())
        != java.lang.Float.floatToIntBits(
            other.getDeltaY())) return false;
    if (getTimestampMs()
        != other.getTimestampMs()) return false;
    if (getSequenceId()
        != other.getSequenceId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DELTA_X_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDeltaX());
    hash = (37 * hash) + DELTA_Y_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDeltaY());
    hash = (37 * hash) + TIMESTAMP_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestampMs());
    hash = (37 * hash) + SEQUENCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSequenceId();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.skymouse.skymouseclient.proto.MouseEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.MouseEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.MouseEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.MouseEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.MouseEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.MouseEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.MouseEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.skymouse.skymouseclient.proto.MouseEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.skymouse.skymouseclient.proto.MouseEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.skymouse.skymouseclient.proto.MouseEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.MouseEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.skymouse.skymouseclient.proto.MouseEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.skymouse.skymouseclient.proto.MouseEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code skymouse.MouseEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:skymouse.MouseEvent)
      com.skymouse.skymouseclient.proto.MouseEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_MouseEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_MouseEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skymouse.skymouseclient.proto.MouseEvent.class, com.skymouse.skymouseclient.proto.MouseEvent.Builder.class);
    }

    // Construct using com.skymouse.skymouseclient.proto.MouseEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      deltaX_ = 0F;
      deltaY_ = 0F;
      timestampMs_ = 0L;
      sequenceId_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_MouseEvent_descriptor;
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.MouseEvent getDefaultInstanceForType() {
      return com.skymouse.skymouseclient.proto.MouseEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.MouseEvent build() {
      com.skymouse.skymouseclient.proto.MouseEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.MouseEvent buildPartial() {
      com.skymouse.skymouseclient.proto.MouseEvent result = new com.skymouse.skymouseclient.proto.MouseEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.skymouse.skymouseclient.proto.MouseEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.deltaX_ = deltaX_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.deltaY_ = deltaY_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timestampMs_ = timestampMs_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sequenceId_ = sequenceId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.skymouse.skymouseclient.proto.MouseEvent) {
        return mergeFrom((com.skymouse.skymouseclient.proto.MouseEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.skymouse.skymouseclient.proto.MouseEvent other) {
      if (other == com.skymouse.skymouseclient.proto.MouseEvent.getDefaultInstance()) return this;
      if (java.lang.Float.floatToRawIntBits(other.getDeltaX()) != 0) {
        setDeltaX(other.getDeltaX());
      }
      if (java.lang.Float.floatToRawIntBits(other.getDeltaY()) != 0) {
        setDeltaY(other.getDeltaY());
      }
      if (other.getTimestampMs() != 0L) {
        setTimestampMs(other.getTimestampMs());
      }
      if (other.getSequenceId() != 0) {
        setSequenceId(other.getSequenceId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              deltaX_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 21: {
              deltaY_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 24: {
              timestampMs_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              sequenceId_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private float deltaX_ ;
    /**
     * <code>float delta_x = 1;</code>
     * @return The deltaX.
     */
    @java.lang.Override
    public float getDeltaX() {
      return deltaX_;
    }
    /**
     * <code>float delta_x = 1;</code>
     * @param value The deltaX to set.
     * @return This builder for chaining.
     */
    public Builder setDeltaX(float value) {

      deltaX_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>float delta_x = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeltaX() {
      bitField0_ = (bitField0_ & ~0x00000001);
      deltaX_ = 0F;
      onChanged();
      return this;
    }

    private float deltaY_ ;
    /**
     * <code>float delta_y = 2;</code>
     * @return The deltaY.
     */
    @java.lang.Override
    public float getDeltaY() {
      return deltaY_;
    }
    /**
     * <code>float delta_y = 2;</code>
     * @param value The deltaY to set.
     * @return This builder for chaining.
     */
    public Builder setDeltaY(float value) {

      deltaY_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float delta_y = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeltaY() {
      bitField0_ = (bitField0_ & ~0x00000002);
      deltaY_ = 0F;
      onChanged();
      return this;
    }

    private long timestampMs_ ;
    /**
     * <code>int64 timestamp_ms = 3;</code>
     * @return The timestampMs.
     */
    @java.lang.Override
    public long getTimestampMs() {
      return timestampMs_;
    }
    /**
     * <code>int64 timestamp_ms = 3;</code>
     * @param value The timestampMs to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampMs(long value) {

      timestampMs_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp_ms = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampMs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timestampMs_ = 0L;
      onChanged();
      return this;
    }

    private int sequenceId_ ;
    /**
     * <code>uint32 sequence_id = 4;</code>
     * @return The sequenceId.
     */
    @java.lang.Override
    public int getSequenceId() {
      return sequenceId_;
    }
    /**
     * <code>uint32 sequence_id = 4;</code>
     * @param value The sequenceId to set.
     * @return This builder for chaining.
     */
    public Builder setSequenceId(int value) {

      sequenceId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 sequence_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSequenceId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sequenceId_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:skymouse.MouseEvent)
  }

  // @@protoc_insertion_point(class_scope:skymouse.MouseEvent)
  private static final com.skymouse.skymouseclient.proto.MouseEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.skymouse.skymouseclient.proto.MouseEvent();
  }

  public static com.skymouse.skymouseclient.proto.MouseEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MouseEvent>
      PARSER = new com.google.protobuf.AbstractParser<MouseEvent>() {
    @java.lang.Override
    public MouseEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MouseEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MouseEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.skymouse.skymouseclient.proto.MouseEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

