// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializemouseEvent")
public inline fun mouseEvent(block: com.skymouse.skymouseclient.proto.MouseEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.MouseEvent =
  com.skymouse.skymouseclient.proto.MouseEventKt.Dsl._create(com.skymouse.skymouseclient.proto.MouseEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.MouseEvent`
 */
public object MouseEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.MouseEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.MouseEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.MouseEvent = _builder.build()

    /**
     * `float delta_x = 1;`
     */
    public var deltaX: kotlin.Float
      @kotlin.jvm.JvmName("getDeltaX")
        get() = _builder.deltaX
      @kotlin.jvm.JvmName("setDeltaX")
        set(value) {
        _builder.deltaX = value
      }
    /**
     * `float delta_x = 1;`
     */
    public fun clearDeltaX() {
      _builder.clearDeltaX()
    }

    /**
     * `float delta_y = 2;`
     */
    public var deltaY: kotlin.Float
      @kotlin.jvm.JvmName("getDeltaY")
        get() = _builder.deltaY
      @kotlin.jvm.JvmName("setDeltaY")
        set(value) {
        _builder.deltaY = value
      }
    /**
     * `float delta_y = 2;`
     */
    public fun clearDeltaY() {
      _builder.clearDeltaY()
    }

    /**
     * `int64 timestamp_ms = 3;`
     */
    public var timestampMs: kotlin.Long
      @kotlin.jvm.JvmName("getTimestampMs")
        get() = _builder.timestampMs
      @kotlin.jvm.JvmName("setTimestampMs")
        set(value) {
        _builder.timestampMs = value
      }
    /**
     * `int64 timestamp_ms = 3;`
     */
    public fun clearTimestampMs() {
      _builder.clearTimestampMs()
    }

    /**
     * `uint32 sequence_id = 4;`
     */
    public var sequenceId: kotlin.Int
      @kotlin.jvm.JvmName("getSequenceId")
        get() = _builder.sequenceId
      @kotlin.jvm.JvmName("setSequenceId")
        set(value) {
        _builder.sequenceId = value
      }
    /**
     * `uint32 sequence_id = 4;`
     */
    public fun clearSequenceId() {
      _builder.clearSequenceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.MouseEvent.copy(block: `com.skymouse.skymouseclient.proto`.MouseEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.MouseEvent =
  `com.skymouse.skymouseclient.proto`.MouseEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

