// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface MouseEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.MouseEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float delta_x = 1;</code>
   * @return The deltaX.
   */
  float getDeltaX();

  /**
   * <code>float delta_y = 2;</code>
   * @return The deltaY.
   */
  float getDeltaY();

  /**
   * <code>int64 timestamp_ms = 3;</code>
   * @return The timestampMs.
   */
  long getTimestampMs();

  /**
   * <code>uint32 sequence_id = 4;</code>
   * @return The sequenceId.
   */
  int getSequenceId();
}
