// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializeping")
public inline fun ping(block: com.skymouse.skymouseclient.proto.PingKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.Ping =
  com.skymouse.skymouseclient.proto.PingKt.Dsl._create(com.skymouse.skymouseclient.proto.Ping.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.Ping`
 */
public object PingKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.Ping.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.Ping.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.Ping = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.Ping.copy(block: `com.skymouse.skymouseclient.proto`.PingKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.Ping =
  `com.skymouse.skymouseclient.proto`.PingKt.Dsl._create(this.toBuilder()).apply { block() }._build()

