// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializepong")
public inline fun pong(block: com.skymouse.skymouseclient.proto.PongKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.Pong =
  com.skymouse.skymouseclient.proto.PongKt.Dsl._create(com.skymouse.skymouseclient.proto.Pong.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.Pong`
 */
public object PongKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.Pong.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.Pong.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.Pong = _builder.build()

    /**
     * `int64 sequence_id = 1;`
     */
    public var sequenceId: kotlin.Long
      @kotlin.jvm.JvmName("getSequenceId")
        get() = _builder.sequenceId
      @kotlin.jvm.JvmName("setSequenceId")
        set(value) {
        _builder.sequenceId = value
      }
    /**
     * `int64 sequence_id = 1;`
     */
    public fun clearSequenceId() {
      _builder.clearSequenceId()
    }

    /**
     * `int64 timestamp_ms = 2;`
     */
    public var timestampMs: kotlin.Long
      @kotlin.jvm.JvmName("getTimestampMs")
        get() = _builder.timestampMs
      @kotlin.jvm.JvmName("setTimestampMs")
        set(value) {
        _builder.timestampMs = value
      }
    /**
     * `int64 timestamp_ms = 2;`
     */
    public fun clearTimestampMs() {
      _builder.clearTimestampMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.Pong.copy(block: `com.skymouse.skymouseclient.proto`.PongKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.Pong =
  `com.skymouse.skymouseclient.proto`.PongKt.Dsl._create(this.toBuilder()).apply { block() }._build()

