// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface ScrollEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.ScrollEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 delta_y = 1;</code>
   * @return The deltaY.
   */
  int getDeltaY();

  /**
   * <code>int64 timestamp_ms = 2;</code>
   * @return The timestampMs.
   */
  long getTimestampMs();
}
