// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializescrollEvent")
public inline fun scrollEvent(block: com.skymouse.skymouseclient.proto.ScrollEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.ScrollEvent =
  com.skymouse.skymouseclient.proto.ScrollEventKt.Dsl._create(com.skymouse.skymouseclient.proto.ScrollEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.ScrollEvent`
 */
public object ScrollEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.ScrollEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.ScrollEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.ScrollEvent = _builder.build()

    /**
     * `int32 delta_y = 1;`
     */
    public var deltaY: kotlin.Int
      @kotlin.jvm.JvmName("getDeltaY")
        get() = _builder.deltaY
      @kotlin.jvm.JvmName("setDeltaY")
        set(value) {
        _builder.deltaY = value
      }
    /**
     * `int32 delta_y = 1;`
     */
    public fun clearDeltaY() {
      _builder.clearDeltaY()
    }

    /**
     * `int64 timestamp_ms = 2;`
     */
    public var timestampMs: kotlin.Long
      @kotlin.jvm.JvmName("getTimestampMs")
        get() = _builder.timestampMs
      @kotlin.jvm.JvmName("setTimestampMs")
        set(value) {
        _builder.timestampMs = value
      }
    /**
     * `int64 timestamp_ms = 2;`
     */
    public fun clearTimestampMs() {
      _builder.clearTimestampMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.ScrollEvent.copy(block: `com.skymouse.skymouseclient.proto`.ScrollEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.ScrollEvent =
  `com.skymouse.skymouseclient.proto`.ScrollEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

