// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

/**
 * Protobuf type {@code skymouse.ServerHello}
 */
@com.google.protobuf.Generated
public final class ServerHello extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:skymouse.ServerHello)
    ServerHelloOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ServerHello");
  }
  // Use ServerHello.newBuilder() to construct.
  private ServerHello(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ServerHello() {
    serverVersion_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_ServerHello_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_ServerHello_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_ServerHello_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.skymouse.skymouseclient.proto.ServerHello.class, com.skymouse.skymouseclient.proto.ServerHello.Builder.class);
  }

  public static final int SERVER_VERSION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serverVersion_ = "";
  /**
   * <code>string server_version = 1;</code>
   * @return The serverVersion.
   */
  @java.lang.Override
  public java.lang.String getServerVersion() {
    java.lang.Object ref = serverVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string server_version = 1;</code>
   * @return The bytes for serverVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServerVersionBytes() {
    java.lang.Object ref = serverVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UDP_PORT_FIELD_NUMBER = 2;
  private int udpPort_ = 0;
  /**
   * <code>int32 udp_port = 2;</code>
   * @return The udpPort.
   */
  @java.lang.Override
  public int getUdpPort() {
    return udpPort_;
  }

  public static final int UDP_TOKEN_FIELD_NUMBER = 3;
  private int udpToken_ = 0;
  /**
   * <code>uint32 udp_token = 3;</code>
   * @return The udpToken.
   */
  @java.lang.Override
  public int getUdpToken() {
    return udpToken_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, serverVersion_);
    }
    if (udpPort_ != 0) {
      output.writeInt32(2, udpPort_);
    }
    if (udpToken_ != 0) {
      output.writeUInt32(3, udpToken_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, serverVersion_);
    }
    if (udpPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, udpPort_);
    }
    if (udpToken_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, udpToken_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.skymouse.skymouseclient.proto.ServerHello)) {
      return super.equals(obj);
    }
    com.skymouse.skymouseclient.proto.ServerHello other = (com.skymouse.skymouseclient.proto.ServerHello) obj;

    if (!getServerVersion()
        .equals(other.getServerVersion())) return false;
    if (getUdpPort()
        != other.getUdpPort()) return false;
    if (getUdpToken()
        != other.getUdpToken()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVER_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getServerVersion().hashCode();
    hash = (37 * hash) + UDP_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getUdpPort();
    hash = (37 * hash) + UDP_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getUdpToken();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.skymouse.skymouseclient.proto.ServerHello parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.ServerHello parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.ServerHello parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.ServerHello parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.ServerHello parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.ServerHello parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.ServerHello parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.skymouse.skymouseclient.proto.ServerHello parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.skymouse.skymouseclient.proto.ServerHello parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.skymouse.skymouseclient.proto.ServerHello parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.ServerHello parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.skymouse.skymouseclient.proto.ServerHello parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.skymouse.skymouseclient.proto.ServerHello prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code skymouse.ServerHello}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:skymouse.ServerHello)
      com.skymouse.skymouseclient.proto.ServerHelloOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_ServerHello_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_ServerHello_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skymouse.skymouseclient.proto.ServerHello.class, com.skymouse.skymouseclient.proto.ServerHello.Builder.class);
    }

    // Construct using com.skymouse.skymouseclient.proto.ServerHello.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      serverVersion_ = "";
      udpPort_ = 0;
      udpToken_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_ServerHello_descriptor;
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ServerHello getDefaultInstanceForType() {
      return com.skymouse.skymouseclient.proto.ServerHello.getDefaultInstance();
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ServerHello build() {
      com.skymouse.skymouseclient.proto.ServerHello result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.ServerHello buildPartial() {
      com.skymouse.skymouseclient.proto.ServerHello result = new com.skymouse.skymouseclient.proto.ServerHello(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.skymouse.skymouseclient.proto.ServerHello result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.serverVersion_ = serverVersion_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.udpPort_ = udpPort_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.udpToken_ = udpToken_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.skymouse.skymouseclient.proto.ServerHello) {
        return mergeFrom((com.skymouse.skymouseclient.proto.ServerHello)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.skymouse.skymouseclient.proto.ServerHello other) {
      if (other == com.skymouse.skymouseclient.proto.ServerHello.getDefaultInstance()) return this;
      if (!other.getServerVersion().isEmpty()) {
        serverVersion_ = other.serverVersion_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getUdpPort() != 0) {
        setUdpPort(other.getUdpPort());
      }
      if (other.getUdpToken() != 0) {
        setUdpToken(other.getUdpToken());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              serverVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              udpPort_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              udpToken_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object serverVersion_ = "";
    /**
     * <code>string server_version = 1;</code>
     * @return The serverVersion.
     */
    public java.lang.String getServerVersion() {
      java.lang.Object ref = serverVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string server_version = 1;</code>
     * @return The bytes for serverVersion.
     */
    public com.google.protobuf.ByteString
        getServerVersionBytes() {
      java.lang.Object ref = serverVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string server_version = 1;</code>
     * @param value The serverVersion to set.
     * @return This builder for chaining.
     */
    public Builder setServerVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serverVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string server_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerVersion() {
      serverVersion_ = getDefaultInstance().getServerVersion();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string server_version = 1;</code>
     * @param value The bytes for serverVersion to set.
     * @return This builder for chaining.
     */
    public Builder setServerVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serverVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int udpPort_ ;
    /**
     * <code>int32 udp_port = 2;</code>
     * @return The udpPort.
     */
    @java.lang.Override
    public int getUdpPort() {
      return udpPort_;
    }
    /**
     * <code>int32 udp_port = 2;</code>
     * @param value The udpPort to set.
     * @return This builder for chaining.
     */
    public Builder setUdpPort(int value) {

      udpPort_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 udp_port = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUdpPort() {
      bitField0_ = (bitField0_ & ~0x00000002);
      udpPort_ = 0;
      onChanged();
      return this;
    }

    private int udpToken_ ;
    /**
     * <code>uint32 udp_token = 3;</code>
     * @return The udpToken.
     */
    @java.lang.Override
    public int getUdpToken() {
      return udpToken_;
    }
    /**
     * <code>uint32 udp_token = 3;</code>
     * @param value The udpToken to set.
     * @return This builder for chaining.
     */
    public Builder setUdpToken(int value) {

      udpToken_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 udp_token = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUdpToken() {
      bitField0_ = (bitField0_ & ~0x00000004);
      udpToken_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:skymouse.ServerHello)
  }

  // @@protoc_insertion_point(class_scope:skymouse.ServerHello)
  private static final com.skymouse.skymouseclient.proto.ServerHello DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.skymouse.skymouseclient.proto.ServerHello();
  }

  public static com.skymouse.skymouseclient.proto.ServerHello getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerHello>
      PARSER = new com.google.protobuf.AbstractParser<ServerHello>() {
    @java.lang.Override
    public ServerHello parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServerHello> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerHello> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.skymouse.skymouseclient.proto.ServerHello getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

