// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializeserverHello")
public inline fun serverHello(block: com.skymouse.skymouseclient.proto.ServerHelloKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.ServerHello =
  com.skymouse.skymouseclient.proto.ServerHelloKt.Dsl._create(com.skymouse.skymouseclient.proto.ServerHello.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.ServerHello`
 */
public object ServerHelloKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.ServerHello.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.ServerHello.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.ServerHello = _builder.build()

    /**
     * `string server_version = 1;`
     */
    public var serverVersion: kotlin.String
      @kotlin.jvm.JvmName("getServerVersion")
        get() = _builder.serverVersion
      @kotlin.jvm.JvmName("setServerVersion")
        set(value) {
        _builder.serverVersion = value
      }
    /**
     * `string server_version = 1;`
     */
    public fun clearServerVersion() {
      _builder.clearServerVersion()
    }

    /**
     * `int32 udp_port = 2;`
     */
    public var udpPort: kotlin.Int
      @kotlin.jvm.JvmName("getUdpPort")
        get() = _builder.udpPort
      @kotlin.jvm.JvmName("setUdpPort")
        set(value) {
        _builder.udpPort = value
      }
    /**
     * `int32 udp_port = 2;`
     */
    public fun clearUdpPort() {
      _builder.clearUdpPort()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.ServerHello.copy(block: `com.skymouse.skymouseclient.proto`.ServerHelloKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.ServerHello =
  `com.skymouse.skymouseclient.proto`.ServerHelloKt.Dsl._create(this.toBuilder()).apply { block() }._build()

