// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializeserverEvent")
public inline fun serverEvent(block: com.skymouse.skymouseclient.proto.ServerEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.ServerEvent =
  com.skymouse.skymouseclient.proto.ServerEventKt.Dsl._create(com.skymouse.skymouseclient.proto.ServerEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.ServerEvent`
 */
public object ServerEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.ServerEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.ServerEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.ServerEvent = _builder.build()

    /**
     * `.skymouse.HapticEventType type = 1;`
     */
    public var type: com.skymouse.skymouseclient.proto.HapticEventType
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    public var typeValue: kotlin.Int
      @kotlin.jvm.JvmName("getTypeValue")
        get() = _builder.typeValue
      @kotlin.jvm.JvmName("setTypeValue")
        set(value) {
        _builder.typeValue = value
      }
    /**
     * `.skymouse.HapticEventType type = 1;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `int64 timestamp_ms = 2;`
     */
    public var timestampMs: kotlin.Long
      @kotlin.jvm.JvmName("getTimestampMs")
        get() = _builder.timestampMs
      @kotlin.jvm.JvmName("setTimestampMs")
        set(value) {
        _builder.timestampMs = value
      }
    /**
     * `int64 timestamp_ms = 2;`
     */
    public fun clearTimestampMs() {
      _builder.clearTimestampMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.ServerEvent.copy(block: `com.skymouse.skymouseclient.proto`.ServerEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.ServerEvent =
  `com.skymouse.skymouseclient.proto`.ServerEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

