// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface ServerEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.ServerEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.skymouse.HapticEventType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.skymouse.HapticEventType type = 1;</code>
   * @return The type.
   */
  com.skymouse.skymouseclient.proto.HapticEventType getType();

  /**
   * <code>int64 timestamp_ms = 2;</code>
   * @return The timestampMs.
   */
  long getTimestampMs();
}
