// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializesetCursorScaleEvent")
public inline fun setCursorScaleEvent(block: com.skymouse.skymouseclient.proto.SetCursorScaleEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.SetCursorScaleEvent =
  com.skymouse.skymouseclient.proto.SetCursorScaleEventKt.Dsl._create(com.skymouse.skymouseclient.proto.SetCursorScaleEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.SetCursorScaleEvent`
 */
public object SetCursorScaleEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.SetCursorScaleEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.SetCursorScaleEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.SetCursorScaleEvent = _builder.build()

    /**
     * `int32 new_cursor_scale = 1;`
     */
    public var newCursorScale: kotlin.Int
      @kotlin.jvm.JvmName("getNewCursorScale")
        get() = _builder.newCursorScale
      @kotlin.jvm.JvmName("setNewCursorScale")
        set(value) {
        _builder.newCursorScale = value
      }
    /**
     * `int32 new_cursor_scale = 1;`
     */
    public fun clearNewCursorScale() {
      _builder.clearNewCursorScale()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.SetCursorScaleEvent.copy(block: `com.skymouse.skymouseclient.proto`.SetCursorScaleEventKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.SetCursorScaleEvent =
  `com.skymouse.skymouseclient.proto`.SetCursorScaleEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

