// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public final class Skymouse extends com.google.protobuf.GeneratedFile {
  private Skymouse() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Skymouse");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_MouseEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_MouseEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_ClickEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_ClickEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_ScrollEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_ScrollEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_MessageToServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_MessageToServer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016skymouse.proto\022\010skymouse\"Y\n\nMouseEvent" +
      "\022\017\n\007delta_x\030\001 \001(\002\022\017\n\007delta_y\030\002 \001(\002\022\024\n\014ti" +
      "mestamp_ms\030\003 \001(\003\022\023\n\013sequence_id\030\004 \001(\r\"o\n" +
      "\nClickEvent\022%\n\006button\030\001 \001(\0162\025.skymouse.M" +
      "ouseButton\022$\n\005state\030\002 \001(\0162\025.skymouse.But" +
      "tonState\022\024\n\014timestamp_ms\030\003 \001(\003\"4\n\013Scroll" +
      "Event\022\017\n\007delta_y\030\001 \001(\005\022\024\n\014timestamp_ms\030\002" +
      " \001(\003\"\221\001\n\017MessageToServer\022%\n\005mouse\030\001 \001(\0132" +
      "\024.skymouse.MouseEventH\000\022%\n\005click\030\002 \001(\0132\024" +
      ".skymouse.ClickEventH\000\022\'\n\006scroll\030\003 \001(\0132\025" +
      ".skymouse.ScrollEventH\000B\007\n\005event*W\n\013Mous" +
      "eButton\022\022\n\016BUTTON_UNKNOWN\020\000\022\017\n\013BUTTON_LE" +
      "FT\020\001\022\020\n\014BUTTON_RIGHT\020\002\022\021\n\rBUTTON_MIDDLE\020" +
      "\003*>\n\013ButtonState\022\021\n\rSTATE_UNKNOWN\020\000\022\016\n\nS" +
      "TATE_DOWN\020\001\022\014\n\010STATE_UP\020\002BY\n!com.skymous" +
      "e.skymouseclient.protoP\001Z2github.com/Tom" +
      "ahawk-Center/SkyMouse/proto;protoapib\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_skymouse_MouseEvent_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_skymouse_MouseEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_MouseEvent_descriptor,
        new java.lang.String[] { "DeltaX", "DeltaY", "TimestampMs", "SequenceId", });
    internal_static_skymouse_ClickEvent_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_skymouse_ClickEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_ClickEvent_descriptor,
        new java.lang.String[] { "Button", "State", "TimestampMs", });
    internal_static_skymouse_ScrollEvent_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_skymouse_ScrollEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_ScrollEvent_descriptor,
        new java.lang.String[] { "DeltaY", "TimestampMs", });
    internal_static_skymouse_MessageToServer_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_skymouse_MessageToServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_MessageToServer_descriptor,
        new java.lang.String[] { "Mouse", "Click", "Scroll", "Event", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
