// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public final class Skymouse extends com.google.protobuf.GeneratedFile {
  private Skymouse() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Skymouse");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_MouseEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_MouseEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_ClickEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_ClickEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_ScrollEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_ScrollEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_Ping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_Ping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_Pong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_Pong_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_ClientHello_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_ClientHello_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_ServerHello_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_ServerHello_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_ServerEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_ServerEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_MessageToServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_MessageToServer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skymouse_MessageToClient_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_skymouse_MessageToClient_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016skymouse.proto\022\010skymouse\"Y\n\nMouseEvent" +
      "\022\017\n\007delta_x\030\001 \001(\002\022\017\n\007delta_y\030\002 \001(\002\022\024\n\014ti" +
      "mestamp_ms\030\003 \001(\003\022\023\n\013sequence_id\030\004 \001(\r\"o\n" +
      "\nClickEvent\022%\n\006button\030\001 \001(\0162\025.skymouse.M" +
      "ouseButton\022$\n\005state\030\002 \001(\0162\025.skymouse.But" +
      "tonState\022\024\n\014timestamp_ms\030\003 \001(\003\"4\n\013Scroll" +
      "Event\022\017\n\007delta_y\030\001 \001(\005\022\024\n\014timestamp_ms\030\002" +
      " \001(\003\"\006\n\004Ping\"\006\n\004Pong\"%\n\013ClientHello\022\026\n\016c" +
      "lient_version\030\001 \001(\t\"7\n\013ServerHello\022\026\n\016se" +
      "rver_version\030\001 \001(\t\022\020\n\010udp_port\030\002 \001(\005\"L\n\013" +
      "ServerEvent\022\'\n\004type\030\001 \001(\0162\031.skymouse.Hap" +
      "ticEventType\022\024\n\014timestamp_ms\030\002 \001(\003\"\200\002\n\017M" +
      "essageToServer\022%\n\005mouse\030\001 \001(\0132\024.skymouse" +
      ".MouseEventH\000\022%\n\005click\030\002 \001(\0132\024.skymouse." +
      "ClickEventH\000\022\'\n\006scroll\030\003 \001(\0132\025.skymouse." +
      "ScrollEventH\000\022-\n\014client_hello\030\004 \001(\0132\025.sk" +
      "ymouse.ClientHelloH\000\022\036\n\004ping\030\005 \001(\0132\016.sky" +
      "mouse.PingH\000\022\036\n\004pong\030\006 \001(\0132\016.skymouse.Po" +
      "ngH\000B\007\n\005event\"x\n\017MessageToClient\022-\n\014serv" +
      "er_hello\030\001 \001(\0132\025.skymouse.ServerHelloH\000\022" +
      "-\n\014server_event\030\002 \001(\0132\025.skymouse.ServerE" +
      "ventH\000B\007\n\005event*W\n\013MouseButton\022\022\n\016BUTTON" +
      "_UNKNOWN\020\000\022\017\n\013BUTTON_LEFT\020\001\022\020\n\014BUTTON_RI" +
      "GHT\020\002\022\021\n\rBUTTON_MIDDLE\020\003*>\n\013ButtonState\022" +
      "\021\n\rSTATE_UNKNOWN\020\000\022\016\n\nSTATE_DOWN\020\001\022\014\n\010ST" +
      "ATE_UP\020\002*S\n\017HapticEventType\022\021\n\rEVENT_UNK" +
      "NOWN\020\000\022\031\n\025EVENT_BORDER_CROSSING\020\001\022\022\n\016EVE" +
      "NT_EDGE_HIT\020\002BY\n!com.skymouse.skymousecl" +
      "ient.protoP\001Z2github.com/Tomahawk-Center" +
      "/SkyMouse/proto;protoapib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_skymouse_MouseEvent_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_skymouse_MouseEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_MouseEvent_descriptor,
        new java.lang.String[] { "DeltaX", "DeltaY", "TimestampMs", "SequenceId", });
    internal_static_skymouse_ClickEvent_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_skymouse_ClickEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_ClickEvent_descriptor,
        new java.lang.String[] { "Button", "State", "TimestampMs", });
    internal_static_skymouse_ScrollEvent_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_skymouse_ScrollEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_ScrollEvent_descriptor,
        new java.lang.String[] { "DeltaY", "TimestampMs", });
    internal_static_skymouse_Ping_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_skymouse_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_Ping_descriptor,
        new java.lang.String[] { });
    internal_static_skymouse_Pong_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_skymouse_Pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_Pong_descriptor,
        new java.lang.String[] { });
    internal_static_skymouse_ClientHello_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_skymouse_ClientHello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_ClientHello_descriptor,
        new java.lang.String[] { "ClientVersion", });
    internal_static_skymouse_ServerHello_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_skymouse_ServerHello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_ServerHello_descriptor,
        new java.lang.String[] { "ServerVersion", "UdpPort", });
    internal_static_skymouse_ServerEvent_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_skymouse_ServerEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_ServerEvent_descriptor,
        new java.lang.String[] { "Type", "TimestampMs", });
    internal_static_skymouse_MessageToServer_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_skymouse_MessageToServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_MessageToServer_descriptor,
        new java.lang.String[] { "Mouse", "Click", "Scroll", "ClientHello", "Ping", "Pong", "Event", });
    internal_static_skymouse_MessageToClient_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_skymouse_MessageToClient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_skymouse_MessageToClient_descriptor,
        new java.lang.String[] { "ServerHello", "ServerEvent", "Event", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
