// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

/**
 * Protobuf type {@code skymouse.UdpMessageToServer}
 */
@com.google.protobuf.Generated
public final class UdpMessageToServer extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:skymouse.UdpMessageToServer)
    UdpMessageToServerOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "UdpMessageToServer");
  }
  // Use UdpMessageToServer.newBuilder() to construct.
  private UdpMessageToServer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UdpMessageToServer() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_UdpMessageToServer_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_UdpMessageToServer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_UdpMessageToServer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.skymouse.skymouseclient.proto.UdpMessageToServer.class, com.skymouse.skymouseclient.proto.UdpMessageToServer.Builder.class);
  }

  private int eventCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object event_;
  public enum EventCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    EMULATOR_EVENT(2),
    EVENT_NOT_SET(0);
    private final int value;
    private EventCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventCase forNumber(int value) {
      switch (value) {
        case 2: return EMULATOR_EVENT;
        case 0: return EVENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EventCase
  getEventCase() {
    return EventCase.forNumber(
        eventCase_);
  }

  public static final int UDP_TOKEN_FIELD_NUMBER = 1;
  private int udpToken_ = 0;
  /**
   * <code>uint32 udp_token = 1;</code>
   * @return The udpToken.
   */
  @java.lang.Override
  public int getUdpToken() {
    return udpToken_;
  }

  public static final int EMULATOR_EVENT_FIELD_NUMBER = 2;
  /**
   * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
   * @return Whether the emulatorEvent field is set.
   */
  @java.lang.Override
  public boolean hasEmulatorEvent() {
    return eventCase_ == 2;
  }
  /**
   * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
   * @return The emulatorEvent.
   */
  @java.lang.Override
  public com.skymouse.skymouseclient.proto.EmulatorEvent getEmulatorEvent() {
    if (eventCase_ == 2) {
       return (com.skymouse.skymouseclient.proto.EmulatorEvent) event_;
    }
    return com.skymouse.skymouseclient.proto.EmulatorEvent.getDefaultInstance();
  }
  /**
   * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
   */
  @java.lang.Override
  public com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder getEmulatorEventOrBuilder() {
    if (eventCase_ == 2) {
       return (com.skymouse.skymouseclient.proto.EmulatorEvent) event_;
    }
    return com.skymouse.skymouseclient.proto.EmulatorEvent.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (udpToken_ != 0) {
      output.writeUInt32(1, udpToken_);
    }
    if (eventCase_ == 2) {
      output.writeMessage(2, (com.skymouse.skymouseclient.proto.EmulatorEvent) event_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (udpToken_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, udpToken_);
    }
    if (eventCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.skymouse.skymouseclient.proto.EmulatorEvent) event_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.skymouse.skymouseclient.proto.UdpMessageToServer)) {
      return super.equals(obj);
    }
    com.skymouse.skymouseclient.proto.UdpMessageToServer other = (com.skymouse.skymouseclient.proto.UdpMessageToServer) obj;

    if (getUdpToken()
        != other.getUdpToken()) return false;
    if (!getEventCase().equals(other.getEventCase())) return false;
    switch (eventCase_) {
      case 2:
        if (!getEmulatorEvent()
            .equals(other.getEmulatorEvent())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UDP_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getUdpToken();
    switch (eventCase_) {
      case 2:
        hash = (37 * hash) + EMULATOR_EVENT_FIELD_NUMBER;
        hash = (53 * hash) + getEmulatorEvent().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.skymouse.skymouseclient.proto.UdpMessageToServer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.UdpMessageToServer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.UdpMessageToServer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.UdpMessageToServer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.UdpMessageToServer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skymouse.skymouseclient.proto.UdpMessageToServer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.UdpMessageToServer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.skymouse.skymouseclient.proto.UdpMessageToServer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.skymouse.skymouseclient.proto.UdpMessageToServer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.skymouse.skymouseclient.proto.UdpMessageToServer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skymouse.skymouseclient.proto.UdpMessageToServer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.skymouse.skymouseclient.proto.UdpMessageToServer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.skymouse.skymouseclient.proto.UdpMessageToServer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code skymouse.UdpMessageToServer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:skymouse.UdpMessageToServer)
      com.skymouse.skymouseclient.proto.UdpMessageToServerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_UdpMessageToServer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_UdpMessageToServer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skymouse.skymouseclient.proto.UdpMessageToServer.class, com.skymouse.skymouseclient.proto.UdpMessageToServer.Builder.class);
    }

    // Construct using com.skymouse.skymouseclient.proto.UdpMessageToServer.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      udpToken_ = 0;
      if (emulatorEventBuilder_ != null) {
        emulatorEventBuilder_.clear();
      }
      eventCase_ = 0;
      event_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.skymouse.skymouseclient.proto.Skymouse.internal_static_skymouse_UdpMessageToServer_descriptor;
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.UdpMessageToServer getDefaultInstanceForType() {
      return com.skymouse.skymouseclient.proto.UdpMessageToServer.getDefaultInstance();
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.UdpMessageToServer build() {
      com.skymouse.skymouseclient.proto.UdpMessageToServer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.skymouse.skymouseclient.proto.UdpMessageToServer buildPartial() {
      com.skymouse.skymouseclient.proto.UdpMessageToServer result = new com.skymouse.skymouseclient.proto.UdpMessageToServer(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.skymouse.skymouseclient.proto.UdpMessageToServer result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.udpToken_ = udpToken_;
      }
    }

    private void buildPartialOneofs(com.skymouse.skymouseclient.proto.UdpMessageToServer result) {
      result.eventCase_ = eventCase_;
      result.event_ = this.event_;
      if (eventCase_ == 2 &&
          emulatorEventBuilder_ != null) {
        result.event_ = emulatorEventBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.skymouse.skymouseclient.proto.UdpMessageToServer) {
        return mergeFrom((com.skymouse.skymouseclient.proto.UdpMessageToServer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.skymouse.skymouseclient.proto.UdpMessageToServer other) {
      if (other == com.skymouse.skymouseclient.proto.UdpMessageToServer.getDefaultInstance()) return this;
      if (other.getUdpToken() != 0) {
        setUdpToken(other.getUdpToken());
      }
      switch (other.getEventCase()) {
        case EMULATOR_EVENT: {
          mergeEmulatorEvent(other.getEmulatorEvent());
          break;
        }
        case EVENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              udpToken_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetEmulatorEventFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int eventCase_ = 0;
    private java.lang.Object event_;
    public EventCase
        getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public Builder clearEvent() {
      eventCase_ = 0;
      event_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int udpToken_ ;
    /**
     * <code>uint32 udp_token = 1;</code>
     * @return The udpToken.
     */
    @java.lang.Override
    public int getUdpToken() {
      return udpToken_;
    }
    /**
     * <code>uint32 udp_token = 1;</code>
     * @param value The udpToken to set.
     * @return This builder for chaining.
     */
    public Builder setUdpToken(int value) {

      udpToken_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 udp_token = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUdpToken() {
      bitField0_ = (bitField0_ & ~0x00000001);
      udpToken_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.skymouse.skymouseclient.proto.EmulatorEvent, com.skymouse.skymouseclient.proto.EmulatorEvent.Builder, com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder> emulatorEventBuilder_;
    /**
     * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
     * @return Whether the emulatorEvent field is set.
     */
    @java.lang.Override
    public boolean hasEmulatorEvent() {
      return eventCase_ == 2;
    }
    /**
     * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
     * @return The emulatorEvent.
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.EmulatorEvent getEmulatorEvent() {
      if (emulatorEventBuilder_ == null) {
        if (eventCase_ == 2) {
          return (com.skymouse.skymouseclient.proto.EmulatorEvent) event_;
        }
        return com.skymouse.skymouseclient.proto.EmulatorEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 2) {
          return emulatorEventBuilder_.getMessage();
        }
        return com.skymouse.skymouseclient.proto.EmulatorEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
     */
    public Builder setEmulatorEvent(com.skymouse.skymouseclient.proto.EmulatorEvent value) {
      if (emulatorEventBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        emulatorEventBuilder_.setMessage(value);
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
     */
    public Builder setEmulatorEvent(
        com.skymouse.skymouseclient.proto.EmulatorEvent.Builder builderForValue) {
      if (emulatorEventBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        emulatorEventBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
     */
    public Builder mergeEmulatorEvent(com.skymouse.skymouseclient.proto.EmulatorEvent value) {
      if (emulatorEventBuilder_ == null) {
        if (eventCase_ == 2 &&
            event_ != com.skymouse.skymouseclient.proto.EmulatorEvent.getDefaultInstance()) {
          event_ = com.skymouse.skymouseclient.proto.EmulatorEvent.newBuilder((com.skymouse.skymouseclient.proto.EmulatorEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 2) {
          emulatorEventBuilder_.mergeFrom(value);
        } else {
          emulatorEventBuilder_.setMessage(value);
        }
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
     */
    public Builder clearEmulatorEvent() {
      if (emulatorEventBuilder_ == null) {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
        }
        emulatorEventBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
     */
    public com.skymouse.skymouseclient.proto.EmulatorEvent.Builder getEmulatorEventBuilder() {
      return internalGetEmulatorEventFieldBuilder().getBuilder();
    }
    /**
     * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
     */
    @java.lang.Override
    public com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder getEmulatorEventOrBuilder() {
      if ((eventCase_ == 2) && (emulatorEventBuilder_ != null)) {
        return emulatorEventBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 2) {
          return (com.skymouse.skymouseclient.proto.EmulatorEvent) event_;
        }
        return com.skymouse.skymouseclient.proto.EmulatorEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.skymouse.skymouseclient.proto.EmulatorEvent, com.skymouse.skymouseclient.proto.EmulatorEvent.Builder, com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder> 
        internalGetEmulatorEventFieldBuilder() {
      if (emulatorEventBuilder_ == null) {
        if (!(eventCase_ == 2)) {
          event_ = com.skymouse.skymouseclient.proto.EmulatorEvent.getDefaultInstance();
        }
        emulatorEventBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.skymouse.skymouseclient.proto.EmulatorEvent, com.skymouse.skymouseclient.proto.EmulatorEvent.Builder, com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder>(
                (com.skymouse.skymouseclient.proto.EmulatorEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 2;
      onChanged();
      return emulatorEventBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:skymouse.UdpMessageToServer)
  }

  // @@protoc_insertion_point(class_scope:skymouse.UdpMessageToServer)
  private static final com.skymouse.skymouseclient.proto.UdpMessageToServer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.skymouse.skymouseclient.proto.UdpMessageToServer();
  }

  public static com.skymouse.skymouseclient.proto.UdpMessageToServer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UdpMessageToServer>
      PARSER = new com.google.protobuf.AbstractParser<UdpMessageToServer>() {
    @java.lang.Override
    public UdpMessageToServer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UdpMessageToServer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UdpMessageToServer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.skymouse.skymouseclient.proto.UdpMessageToServer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

