// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface UdpMessageToServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.UdpMessageToServer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 udp_token = 1;</code>
   * @return The udpToken.
   */
  int getUdpToken();

  /**
   * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
   * @return Whether the emulatorEvent field is set.
   */
  boolean hasEmulatorEvent();
  /**
   * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
   * @return The emulatorEvent.
   */
  com.skymouse.skymouseclient.proto.EmulatorEvent getEmulatorEvent();
  /**
   * <code>.skymouse.EmulatorEvent emulator_event = 2;</code>
   */
  com.skymouse.skymouseclient.proto.EmulatorEventOrBuilder getEmulatorEventOrBuilder();

  /**
   * <code>.skymouse.Ping ping = 3;</code>
   * @return Whether the ping field is set.
   */
  boolean hasPing();
  /**
   * <code>.skymouse.Ping ping = 3;</code>
   * @return The ping.
   */
  com.skymouse.skymouseclient.proto.Ping getPing();
  /**
   * <code>.skymouse.Ping ping = 3;</code>
   */
  com.skymouse.skymouseclient.proto.PingOrBuilder getPingOrBuilder();

  com.skymouse.skymouseclient.proto.UdpMessageToServer.EventCase getEventCase();
}
