// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto
// Protobuf Java Version: 4.35.1

package com.skymouse.skymouseclient.proto;

@com.google.protobuf.Generated
public interface UdpMessageToServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:skymouse.UdpMessageToServer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 udp_token = 1;</code>
   * @return The udpToken.
   */
  int getUdpToken();

  /**
   * <code>.skymouse.MouseEvent mouse = 2;</code>
   * @return Whether the mouse field is set.
   */
  boolean hasMouse();
  /**
   * <code>.skymouse.MouseEvent mouse = 2;</code>
   * @return The mouse.
   */
  com.skymouse.skymouseclient.proto.MouseEvent getMouse();
  /**
   * <code>.skymouse.MouseEvent mouse = 2;</code>
   */
  com.skymouse.skymouseclient.proto.MouseEventOrBuilder getMouseOrBuilder();

  com.skymouse.skymouseclient.proto.UdpMessageToServer.EventCase getEventCase();
}
