// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializeudpMessageToServer")
public inline fun udpMessageToServer(block: com.skymouse.skymouseclient.proto.UdpMessageToServerKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.UdpMessageToServer =
  com.skymouse.skymouseclient.proto.UdpMessageToServerKt.Dsl._create(com.skymouse.skymouseclient.proto.UdpMessageToServer.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.UdpMessageToServer`
 */
public object UdpMessageToServerKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.UdpMessageToServer.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.UdpMessageToServer.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.UdpMessageToServer = _builder.build()

    /**
     * `uint32 udp_token = 1;`
     */
    public var udpToken: kotlin.Int
      @kotlin.jvm.JvmName("getUdpToken")
        get() = _builder.udpToken
      @kotlin.jvm.JvmName("setUdpToken")
        set(value) {
        _builder.udpToken = value
      }
    /**
     * `uint32 udp_token = 1;`
     */
    public fun clearUdpToken() {
      _builder.clearUdpToken()
    }

    /**
     * `.skymouse.EmulatorEvent emulator_event = 2;`
     */
    public var emulatorEvent: com.skymouse.skymouseclient.proto.EmulatorEvent
      @kotlin.jvm.JvmName("getEmulatorEvent")
        get() = _builder.emulatorEvent
      @kotlin.jvm.JvmName("setEmulatorEvent")
        set(value) {
        _builder.emulatorEvent = value
      }
    /**
     * `.skymouse.EmulatorEvent emulator_event = 2;`
     */
    public fun clearEmulatorEvent() {
      _builder.clearEmulatorEvent()
    }
    /**
     * `.skymouse.EmulatorEvent emulator_event = 2;`
     * @return Whether the emulatorEvent field is set.
     */
    public fun hasEmulatorEvent(): kotlin.Boolean {
      return _builder.hasEmulatorEvent()
    }
    public val eventCase: com.skymouse.skymouseclient.proto.UdpMessageToServer.EventCase
    @kotlin.jvm.JvmName("getEventCase")
      get() = _builder.getEventCase()

    public fun clearEvent() {
      _builder.clearEvent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.UdpMessageToServer.copy(block: `com.skymouse.skymouseclient.proto`.UdpMessageToServerKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.UdpMessageToServer =
  `com.skymouse.skymouseclient.proto`.UdpMessageToServerKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.skymouse.skymouseclient.proto.UdpMessageToServerOrBuilder.emulatorEventOrNull: com.skymouse.skymouseclient.proto.EmulatorEvent?
  get() = if (hasEmulatorEvent()) getEmulatorEvent() else null

