// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skymouse.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.skymouse.skymouseclient.proto;

@kotlin.jvm.JvmName("-initializeudpMessageToServer")
public inline fun udpMessageToServer(block: com.skymouse.skymouseclient.proto.UdpMessageToServerKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.UdpMessageToServer =
  com.skymouse.skymouseclient.proto.UdpMessageToServerKt.Dsl._create(com.skymouse.skymouseclient.proto.UdpMessageToServer.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `skymouse.UdpMessageToServer`
 */
public object UdpMessageToServerKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.skymouse.skymouseclient.proto.UdpMessageToServer.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.skymouse.skymouseclient.proto.UdpMessageToServer.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.skymouse.skymouseclient.proto.UdpMessageToServer = _builder.build()

    /**
     * `uint32 udp_token = 1;`
     */
    public var udpToken: kotlin.Int
      @kotlin.jvm.JvmName("getUdpToken")
        get() = _builder.udpToken
      @kotlin.jvm.JvmName("setUdpToken")
        set(value) {
        _builder.udpToken = value
      }
    /**
     * `uint32 udp_token = 1;`
     */
    public fun clearUdpToken() {
      _builder.clearUdpToken()
    }

    /**
     * `.skymouse.MouseEvent mouse = 2;`
     */
    public var mouse: com.skymouse.skymouseclient.proto.MouseEvent
      @kotlin.jvm.JvmName("getMouse")
        get() = _builder.mouse
      @kotlin.jvm.JvmName("setMouse")
        set(value) {
        _builder.mouse = value
      }
    /**
     * `.skymouse.MouseEvent mouse = 2;`
     */
    public fun clearMouse() {
      _builder.clearMouse()
    }
    /**
     * `.skymouse.MouseEvent mouse = 2;`
     * @return Whether the mouse field is set.
     */
    public fun hasMouse(): kotlin.Boolean {
      return _builder.hasMouse()
    }
    public val eventCase: com.skymouse.skymouseclient.proto.UdpMessageToServer.EventCase
    @kotlin.jvm.JvmName("getEventCase")
      get() = _builder.getEventCase()

    public fun clearEvent() {
      _builder.clearEvent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.skymouse.skymouseclient.proto.UdpMessageToServer.copy(block: `com.skymouse.skymouseclient.proto`.UdpMessageToServerKt.Dsl.() -> kotlin.Unit): com.skymouse.skymouseclient.proto.UdpMessageToServer =
  `com.skymouse.skymouseclient.proto`.UdpMessageToServerKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.skymouse.skymouseclient.proto.UdpMessageToServerOrBuilder.mouseOrNull: com.skymouse.skymouseclient.proto.MouseEvent?
  get() = if (hasMouse()) getMouse() else null

