// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: skymouse.proto

package protoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MouseButton int32

const (
	MouseButton_BUTTON_UNKNOWN MouseButton = 0
	MouseButton_BUTTON_LEFT    MouseButton = 1
	MouseButton_BUTTON_RIGHT   MouseButton = 2
	MouseButton_BUTTON_MIDDLE  MouseButton = 3
)

// Enum value maps for MouseButton.
var (
	MouseButton_name = map[int32]string{
		0: "BUTTON_UNKNOWN",
		1: "BUTTON_LEFT",
		2: "BUTTON_RIGHT",
		3: "BUTTON_MIDDLE",
	}
	MouseButton_value = map[string]int32{
		"BUTTON_UNKNOWN": 0,
		"BUTTON_LEFT":    1,
		"BUTTON_RIGHT":   2,
		"BUTTON_MIDDLE":  3,
	}
)

func (x MouseButton) Enum() *MouseButton {
	p := new(MouseButton)
	*p = x
	return p
}

func (x MouseButton) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MouseButton) Descriptor() protoreflect.EnumDescriptor {
	return file_skymouse_proto_enumTypes[0].Descriptor()
}

func (MouseButton) Type() protoreflect.EnumType {
	return &file_skymouse_proto_enumTypes[0]
}

func (x MouseButton) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MouseButton.Descriptor instead.
func (MouseButton) EnumDescriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{0}
}

type ButtonState int32

const (
	ButtonState_STATE_UNKNOWN ButtonState = 0
	ButtonState_STATE_DOWN    ButtonState = 1
	ButtonState_STATE_UP      ButtonState = 2
)

// Enum value maps for ButtonState.
var (
	ButtonState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "STATE_DOWN",
		2: "STATE_UP",
	}
	ButtonState_value = map[string]int32{
		"STATE_UNKNOWN": 0,
		"STATE_DOWN":    1,
		"STATE_UP":      2,
	}
)

func (x ButtonState) Enum() *ButtonState {
	p := new(ButtonState)
	*p = x
	return p
}

func (x ButtonState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ButtonState) Descriptor() protoreflect.EnumDescriptor {
	return file_skymouse_proto_enumTypes[1].Descriptor()
}

func (ButtonState) Type() protoreflect.EnumType {
	return &file_skymouse_proto_enumTypes[1]
}

func (x ButtonState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ButtonState.Descriptor instead.
func (ButtonState) EnumDescriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{1}
}

type KeyboardKey int32

const (
	KeyboardKey_KEY_UNKNOWN     KeyboardKey = 0
	KeyboardKey_KEY_ENTER       KeyboardKey = 1
	KeyboardKey_KEY_BACKSPACE   KeyboardKey = 2
	KeyboardKey_KEY_VOL_DOWN    KeyboardKey = 3
	KeyboardKey_KEY_VOL_UP      KeyboardKey = 4
	KeyboardKey_KEY_VOL_MUTE    KeyboardKey = 5
	KeyboardKey_KEY_AUDIO_PAUSE KeyboardKey = 6
	KeyboardKey_KEY_AUDIO_PREV  KeyboardKey = 7
	KeyboardKey_KEY_AUDIO_NEXT  KeyboardKey = 8
)

// Enum value maps for KeyboardKey.
var (
	KeyboardKey_name = map[int32]string{
		0: "KEY_UNKNOWN",
		1: "KEY_ENTER",
		2: "KEY_BACKSPACE",
		3: "KEY_VOL_DOWN",
		4: "KEY_VOL_UP",
		5: "KEY_VOL_MUTE",
		6: "KEY_AUDIO_PAUSE",
		7: "KEY_AUDIO_PREV",
		8: "KEY_AUDIO_NEXT",
	}
	KeyboardKey_value = map[string]int32{
		"KEY_UNKNOWN":     0,
		"KEY_ENTER":       1,
		"KEY_BACKSPACE":   2,
		"KEY_VOL_DOWN":    3,
		"KEY_VOL_UP":      4,
		"KEY_VOL_MUTE":    5,
		"KEY_AUDIO_PAUSE": 6,
		"KEY_AUDIO_PREV":  7,
		"KEY_AUDIO_NEXT":  8,
	}
)

func (x KeyboardKey) Enum() *KeyboardKey {
	p := new(KeyboardKey)
	*p = x
	return p
}

func (x KeyboardKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyboardKey) Descriptor() protoreflect.EnumDescriptor {
	return file_skymouse_proto_enumTypes[2].Descriptor()
}

func (KeyboardKey) Type() protoreflect.EnumType {
	return &file_skymouse_proto_enumTypes[2]
}

func (x KeyboardKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyboardKey.Descriptor instead.
func (KeyboardKey) EnumDescriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{2}
}

type HapticEventType int32

const (
	HapticEventType_EVENT_UNKNOWN         HapticEventType = 0
	HapticEventType_EVENT_BORDER_CROSSING HapticEventType = 1
	HapticEventType_EVENT_EDGE_HIT        HapticEventType = 2
)

// Enum value maps for HapticEventType.
var (
	HapticEventType_name = map[int32]string{
		0: "EVENT_UNKNOWN",
		1: "EVENT_BORDER_CROSSING",
		2: "EVENT_EDGE_HIT",
	}
	HapticEventType_value = map[string]int32{
		"EVENT_UNKNOWN":         0,
		"EVENT_BORDER_CROSSING": 1,
		"EVENT_EDGE_HIT":        2,
	}
)

func (x HapticEventType) Enum() *HapticEventType {
	p := new(HapticEventType)
	*p = x
	return p
}

func (x HapticEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HapticEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_skymouse_proto_enumTypes[3].Descriptor()
}

func (HapticEventType) Type() protoreflect.EnumType {
	return &file_skymouse_proto_enumTypes[3]
}

func (x HapticEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HapticEventType.Descriptor instead.
func (HapticEventType) EnumDescriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{3}
}

type CommandEvent int32

const (
	CommandEvent_COMMAND_UNKNOWN     CommandEvent = 0
	CommandEvent_COMMAND_SHUT_DOWN   CommandEvent = 1
	CommandEvent_COMMAND_SLEEP       CommandEvent = 2
	CommandEvent_COMMAND_LOCK_SCREEN CommandEvent = 3
)

// Enum value maps for CommandEvent.
var (
	CommandEvent_name = map[int32]string{
		0: "COMMAND_UNKNOWN",
		1: "COMMAND_SHUT_DOWN",
		2: "COMMAND_SLEEP",
		3: "COMMAND_LOCK_SCREEN",
	}
	CommandEvent_value = map[string]int32{
		"COMMAND_UNKNOWN":     0,
		"COMMAND_SHUT_DOWN":   1,
		"COMMAND_SLEEP":       2,
		"COMMAND_LOCK_SCREEN": 3,
	}
)

func (x CommandEvent) Enum() *CommandEvent {
	p := new(CommandEvent)
	*p = x
	return p
}

func (x CommandEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_skymouse_proto_enumTypes[4].Descriptor()
}

func (CommandEvent) Type() protoreflect.EnumType {
	return &file_skymouse_proto_enumTypes[4]
}

func (x CommandEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandEvent.Descriptor instead.
func (CommandEvent) EnumDescriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{4}
}

type MouseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeltaX        float32                `protobuf:"fixed32,1,opt,name=delta_x,json=deltaX,proto3" json:"delta_x,omitempty"`
	DeltaY        float32                `protobuf:"fixed32,2,opt,name=delta_y,json=deltaY,proto3" json:"delta_y,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	SequenceId    uint32                 `protobuf:"varint,4,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MouseEvent) Reset() {
	*x = MouseEvent{}
	mi := &file_skymouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MouseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseEvent) ProtoMessage() {}

func (x *MouseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseEvent.ProtoReflect.Descriptor instead.
func (*MouseEvent) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{0}
}

func (x *MouseEvent) GetDeltaX() float32 {
	if x != nil {
		return x.DeltaX
	}
	return 0
}

func (x *MouseEvent) GetDeltaY() float32 {
	if x != nil {
		return x.DeltaY
	}
	return 0
}

func (x *MouseEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *MouseEvent) GetSequenceId() uint32 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

type ClickEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Button        MouseButton            `protobuf:"varint,1,opt,name=button,proto3,enum=skymouse.MouseButton" json:"button,omitempty"`
	State         ButtonState            `protobuf:"varint,2,opt,name=state,proto3,enum=skymouse.ButtonState" json:"state,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickEvent) Reset() {
	*x = ClickEvent{}
	mi := &file_skymouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickEvent) ProtoMessage() {}

func (x *ClickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickEvent.ProtoReflect.Descriptor instead.
func (*ClickEvent) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{1}
}

func (x *ClickEvent) GetButton() MouseButton {
	if x != nil {
		return x.Button
	}
	return MouseButton_BUTTON_UNKNOWN
}

func (x *ClickEvent) GetState() ButtonState {
	if x != nil {
		return x.State
	}
	return ButtonState_STATE_UNKNOWN
}

func (x *ClickEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type ScrollEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeltaY        int32                  `protobuf:"varint,1,opt,name=delta_y,json=deltaY,proto3" json:"delta_y,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrollEvent) Reset() {
	*x = ScrollEvent{}
	mi := &file_skymouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrollEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollEvent) ProtoMessage() {}

func (x *ScrollEvent) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollEvent.ProtoReflect.Descriptor instead.
func (*ScrollEvent) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{2}
}

func (x *ScrollEvent) GetDeltaY() int32 {
	if x != nil {
		return x.DeltaY
	}
	return 0
}

func (x *ScrollEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type KeyboardStringEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardStringEvent) Reset() {
	*x = KeyboardStringEvent{}
	mi := &file_skymouse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardStringEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardStringEvent) ProtoMessage() {}

func (x *KeyboardStringEvent) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardStringEvent.ProtoReflect.Descriptor instead.
func (*KeyboardStringEvent) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{3}
}

func (x *KeyboardStringEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *KeyboardStringEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type KeyboardTapEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           KeyboardKey            `protobuf:"varint,1,opt,name=key,proto3,enum=skymouse.KeyboardKey" json:"key,omitempty"`
	State         ButtonState            `protobuf:"varint,2,opt,name=state,proto3,enum=skymouse.ButtonState" json:"state,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardTapEvent) Reset() {
	*x = KeyboardTapEvent{}
	mi := &file_skymouse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardTapEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardTapEvent) ProtoMessage() {}

func (x *KeyboardTapEvent) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardTapEvent.ProtoReflect.Descriptor instead.
func (*KeyboardTapEvent) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{4}
}

func (x *KeyboardTapEvent) GetKey() KeyboardKey {
	if x != nil {
		return x.Key
	}
	return KeyboardKey_KEY_UNKNOWN
}

func (x *KeyboardTapEvent) GetState() ButtonState {
	if x != nil {
		return x.State
	}
	return ButtonState_STATE_UNKNOWN
}

func (x *KeyboardTapEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceId    int64                  `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_skymouse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{5}
}

func (x *Ping) GetSequenceId() int64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *Ping) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceId    int64                  `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_skymouse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{6}
}

func (x *Pong) GetSequenceId() int64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *Pong) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_skymouse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{7}
}

func (x *ClientHello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type ServerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion string                 `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	UdpPort       int32                  `protobuf:"varint,2,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	UdpToken      uint32                 `protobuf:"varint,3,opt,name=udp_token,json=udpToken,proto3" json:"udp_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_skymouse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{8}
}

func (x *ServerHello) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *ServerHello) GetUdpPort() int32 {
	if x != nil {
		return x.UdpPort
	}
	return 0
}

func (x *ServerHello) GetUdpToken() uint32 {
	if x != nil {
		return x.UdpToken
	}
	return 0
}

type ClipboardShareEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ClipboardShareEvent_Text
	Content       isClipboardShareEvent_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipboardShareEvent) Reset() {
	*x = ClipboardShareEvent{}
	mi := &file_skymouse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipboardShareEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardShareEvent) ProtoMessage() {}

func (x *ClipboardShareEvent) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardShareEvent.ProtoReflect.Descriptor instead.
func (*ClipboardShareEvent) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{9}
}

func (x *ClipboardShareEvent) GetContent() isClipboardShareEvent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ClipboardShareEvent) GetText() string {
	if x != nil {
		if x, ok := x.Content.(*ClipboardShareEvent_Text); ok {
			return x.Text
		}
	}
	return ""
}

type isClipboardShareEvent_Content interface {
	isClipboardShareEvent_Content()
}

type ClipboardShareEvent_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"` // for images in future updates
}

func (*ClipboardShareEvent_Text) isClipboardShareEvent_Content() {}

type SetCursorScaleEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewCursorScale int32                  `protobuf:"varint,1,opt,name=new_cursor_scale,json=newCursorScale,proto3" json:"new_cursor_scale,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetCursorScaleEvent) Reset() {
	*x = SetCursorScaleEvent{}
	mi := &file_skymouse_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCursorScaleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCursorScaleEvent) ProtoMessage() {}

func (x *SetCursorScaleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCursorScaleEvent.ProtoReflect.Descriptor instead.
func (*SetCursorScaleEvent) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{10}
}

func (x *SetCursorScaleEvent) GetNewCursorScale() int32 {
	if x != nil {
		return x.NewCursorScale
	}
	return 0
}

type GetCursorScaleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCursorScaleEvent) Reset() {
	*x = GetCursorScaleEvent{}
	mi := &file_skymouse_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCursorScaleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCursorScaleEvent) ProtoMessage() {}

func (x *GetCursorScaleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCursorScaleEvent.ProtoReflect.Descriptor instead.
func (*GetCursorScaleEvent) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{11}
}

type CurrentCursorScaleAnswer struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CurrentCursorScale int32                  `protobuf:"varint,1,opt,name=current_cursor_scale,json=currentCursorScale,proto3" json:"current_cursor_scale,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CurrentCursorScaleAnswer) Reset() {
	*x = CurrentCursorScaleAnswer{}
	mi := &file_skymouse_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentCursorScaleAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentCursorScaleAnswer) ProtoMessage() {}

func (x *CurrentCursorScaleAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentCursorScaleAnswer.ProtoReflect.Descriptor instead.
func (*CurrentCursorScaleAnswer) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{12}
}

func (x *CurrentCursorScaleAnswer) GetCurrentCursorScale() int32 {
	if x != nil {
		return x.CurrentCursorScale
	}
	return 0
}

type ServerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          HapticEventType        `protobuf:"varint,1,opt,name=type,proto3,enum=skymouse.HapticEventType" json:"type,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_skymouse_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{13}
}

func (x *ServerEvent) GetType() HapticEventType {
	if x != nil {
		return x.Type
	}
	return HapticEventType_EVENT_UNKNOWN
}

func (x *ServerEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type EmulatorEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*EmulatorEvent_Mouse
	//	*EmulatorEvent_Click
	//	*EmulatorEvent_Scroll
	//	*EmulatorEvent_KeyboardStringEvent
	//	*EmulatorEvent_KeyboardTapEvent
	Event         isEmulatorEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmulatorEvent) Reset() {
	*x = EmulatorEvent{}
	mi := &file_skymouse_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmulatorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmulatorEvent) ProtoMessage() {}

func (x *EmulatorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmulatorEvent.ProtoReflect.Descriptor instead.
func (*EmulatorEvent) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{14}
}

func (x *EmulatorEvent) GetEvent() isEmulatorEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EmulatorEvent) GetMouse() *MouseEvent {
	if x != nil {
		if x, ok := x.Event.(*EmulatorEvent_Mouse); ok {
			return x.Mouse
		}
	}
	return nil
}

func (x *EmulatorEvent) GetClick() *ClickEvent {
	if x != nil {
		if x, ok := x.Event.(*EmulatorEvent_Click); ok {
			return x.Click
		}
	}
	return nil
}

func (x *EmulatorEvent) GetScroll() *ScrollEvent {
	if x != nil {
		if x, ok := x.Event.(*EmulatorEvent_Scroll); ok {
			return x.Scroll
		}
	}
	return nil
}

func (x *EmulatorEvent) GetKeyboardStringEvent() *KeyboardStringEvent {
	if x != nil {
		if x, ok := x.Event.(*EmulatorEvent_KeyboardStringEvent); ok {
			return x.KeyboardStringEvent
		}
	}
	return nil
}

func (x *EmulatorEvent) GetKeyboardTapEvent() *KeyboardTapEvent {
	if x != nil {
		if x, ok := x.Event.(*EmulatorEvent_KeyboardTapEvent); ok {
			return x.KeyboardTapEvent
		}
	}
	return nil
}

type isEmulatorEvent_Event interface {
	isEmulatorEvent_Event()
}

type EmulatorEvent_Mouse struct {
	Mouse *MouseEvent `protobuf:"bytes,1,opt,name=mouse,proto3,oneof"`
}

type EmulatorEvent_Click struct {
	Click *ClickEvent `protobuf:"bytes,2,opt,name=click,proto3,oneof"`
}

type EmulatorEvent_Scroll struct {
	Scroll *ScrollEvent `protobuf:"bytes,3,opt,name=scroll,proto3,oneof"`
}

type EmulatorEvent_KeyboardStringEvent struct {
	KeyboardStringEvent *KeyboardStringEvent `protobuf:"bytes,4,opt,name=keyboard_string_event,json=keyboardStringEvent,proto3,oneof"`
}

type EmulatorEvent_KeyboardTapEvent struct {
	KeyboardTapEvent *KeyboardTapEvent `protobuf:"bytes,5,opt,name=keyboard_tap_event,json=keyboardTapEvent,proto3,oneof"`
}

func (*EmulatorEvent_Mouse) isEmulatorEvent_Event() {}

func (*EmulatorEvent_Click) isEmulatorEvent_Event() {}

func (*EmulatorEvent_Scroll) isEmulatorEvent_Event() {}

func (*EmulatorEvent_KeyboardStringEvent) isEmulatorEvent_Event() {}

func (*EmulatorEvent_KeyboardTapEvent) isEmulatorEvent_Event() {}

type MessageToServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*MessageToServer_ClientHello
	//	*MessageToServer_EmulatorEvent
	//	*MessageToServer_Ping
	//	*MessageToServer_Pong
	//	*MessageToServer_Command
	//	*MessageToServer_ClipboardShare
	//	*MessageToServer_GetCursorScale
	//	*MessageToServer_SetCursorScale
	Event         isMessageToServer_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageToServer) Reset() {
	*x = MessageToServer{}
	mi := &file_skymouse_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageToServer) ProtoMessage() {}

func (x *MessageToServer) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageToServer.ProtoReflect.Descriptor instead.
func (*MessageToServer) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{15}
}

func (x *MessageToServer) GetEvent() isMessageToServer_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *MessageToServer) GetClientHello() *ClientHello {
	if x != nil {
		if x, ok := x.Event.(*MessageToServer_ClientHello); ok {
			return x.ClientHello
		}
	}
	return nil
}

func (x *MessageToServer) GetEmulatorEvent() *EmulatorEvent {
	if x != nil {
		if x, ok := x.Event.(*MessageToServer_EmulatorEvent); ok {
			return x.EmulatorEvent
		}
	}
	return nil
}

func (x *MessageToServer) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Event.(*MessageToServer_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *MessageToServer) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Event.(*MessageToServer_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *MessageToServer) GetCommand() CommandEvent {
	if x != nil {
		if x, ok := x.Event.(*MessageToServer_Command); ok {
			return x.Command
		}
	}
	return CommandEvent_COMMAND_UNKNOWN
}

func (x *MessageToServer) GetClipboardShare() *ClipboardShareEvent {
	if x != nil {
		if x, ok := x.Event.(*MessageToServer_ClipboardShare); ok {
			return x.ClipboardShare
		}
	}
	return nil
}

func (x *MessageToServer) GetGetCursorScale() *GetCursorScaleEvent {
	if x != nil {
		if x, ok := x.Event.(*MessageToServer_GetCursorScale); ok {
			return x.GetCursorScale
		}
	}
	return nil
}

func (x *MessageToServer) GetSetCursorScale() *SetCursorScaleEvent {
	if x != nil {
		if x, ok := x.Event.(*MessageToServer_SetCursorScale); ok {
			return x.SetCursorScale
		}
	}
	return nil
}

type isMessageToServer_Event interface {
	isMessageToServer_Event()
}

type MessageToServer_ClientHello struct {
	ClientHello *ClientHello `protobuf:"bytes,1,opt,name=client_hello,json=clientHello,proto3,oneof"`
}

type MessageToServer_EmulatorEvent struct {
	EmulatorEvent *EmulatorEvent `protobuf:"bytes,2,opt,name=emulator_event,json=emulatorEvent,proto3,oneof"`
}

type MessageToServer_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type MessageToServer_Pong struct {
	Pong *Pong `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

type MessageToServer_Command struct {
	Command CommandEvent `protobuf:"varint,5,opt,name=command,proto3,enum=skymouse.CommandEvent,oneof"`
}

type MessageToServer_ClipboardShare struct {
	ClipboardShare *ClipboardShareEvent `protobuf:"bytes,6,opt,name=clipboard_share,json=clipboardShare,proto3,oneof"`
}

type MessageToServer_GetCursorScale struct {
	GetCursorScale *GetCursorScaleEvent `protobuf:"bytes,7,opt,name=get_cursor_scale,json=getCursorScale,proto3,oneof"`
}

type MessageToServer_SetCursorScale struct {
	SetCursorScale *SetCursorScaleEvent `protobuf:"bytes,8,opt,name=set_cursor_scale,json=setCursorScale,proto3,oneof"`
}

func (*MessageToServer_ClientHello) isMessageToServer_Event() {}

func (*MessageToServer_EmulatorEvent) isMessageToServer_Event() {}

func (*MessageToServer_Ping) isMessageToServer_Event() {}

func (*MessageToServer_Pong) isMessageToServer_Event() {}

func (*MessageToServer_Command) isMessageToServer_Event() {}

func (*MessageToServer_ClipboardShare) isMessageToServer_Event() {}

func (*MessageToServer_GetCursorScale) isMessageToServer_Event() {}

func (*MessageToServer_SetCursorScale) isMessageToServer_Event() {}

type UdpMessageToServer struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UdpToken uint32                 `protobuf:"varint,1,opt,name=udp_token,json=udpToken,proto3" json:"udp_token,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*UdpMessageToServer_EmulatorEvent
	//	*UdpMessageToServer_Ping
	Event         isUdpMessageToServer_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UdpMessageToServer) Reset() {
	*x = UdpMessageToServer{}
	mi := &file_skymouse_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UdpMessageToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpMessageToServer) ProtoMessage() {}

func (x *UdpMessageToServer) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpMessageToServer.ProtoReflect.Descriptor instead.
func (*UdpMessageToServer) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{16}
}

func (x *UdpMessageToServer) GetUdpToken() uint32 {
	if x != nil {
		return x.UdpToken
	}
	return 0
}

func (x *UdpMessageToServer) GetEvent() isUdpMessageToServer_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *UdpMessageToServer) GetEmulatorEvent() *EmulatorEvent {
	if x != nil {
		if x, ok := x.Event.(*UdpMessageToServer_EmulatorEvent); ok {
			return x.EmulatorEvent
		}
	}
	return nil
}

func (x *UdpMessageToServer) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Event.(*UdpMessageToServer_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isUdpMessageToServer_Event interface {
	isUdpMessageToServer_Event()
}

type UdpMessageToServer_EmulatorEvent struct {
	EmulatorEvent *EmulatorEvent `protobuf:"bytes,2,opt,name=emulator_event,json=emulatorEvent,proto3,oneof"`
}

type UdpMessageToServer_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*UdpMessageToServer_EmulatorEvent) isUdpMessageToServer_Event() {}

func (*UdpMessageToServer_Ping) isUdpMessageToServer_Event() {}

type MessageToClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*MessageToClient_ServerHello
	//	*MessageToClient_ServerEvent
	//	*MessageToClient_Pong
	//	*MessageToClient_CurrentCursorScaleAnswer
	Event         isMessageToClient_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageToClient) Reset() {
	*x = MessageToClient{}
	mi := &file_skymouse_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageToClient) ProtoMessage() {}

func (x *MessageToClient) ProtoReflect() protoreflect.Message {
	mi := &file_skymouse_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageToClient.ProtoReflect.Descriptor instead.
func (*MessageToClient) Descriptor() ([]byte, []int) {
	return file_skymouse_proto_rawDescGZIP(), []int{17}
}

func (x *MessageToClient) GetEvent() isMessageToClient_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *MessageToClient) GetServerHello() *ServerHello {
	if x != nil {
		if x, ok := x.Event.(*MessageToClient_ServerHello); ok {
			return x.ServerHello
		}
	}
	return nil
}

func (x *MessageToClient) GetServerEvent() *ServerEvent {
	if x != nil {
		if x, ok := x.Event.(*MessageToClient_ServerEvent); ok {
			return x.ServerEvent
		}
	}
	return nil
}

func (x *MessageToClient) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Event.(*MessageToClient_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *MessageToClient) GetCurrentCursorScaleAnswer() *CurrentCursorScaleAnswer {
	if x != nil {
		if x, ok := x.Event.(*MessageToClient_CurrentCursorScaleAnswer); ok {
			return x.CurrentCursorScaleAnswer
		}
	}
	return nil
}

type isMessageToClient_Event interface {
	isMessageToClient_Event()
}

type MessageToClient_ServerHello struct {
	ServerHello *ServerHello `protobuf:"bytes,1,opt,name=server_hello,json=serverHello,proto3,oneof"`
}

type MessageToClient_ServerEvent struct {
	ServerEvent *ServerEvent `protobuf:"bytes,2,opt,name=server_event,json=serverEvent,proto3,oneof"`
}

type MessageToClient_Pong struct {
	Pong *Pong `protobuf:"bytes,3,opt,name=pong,proto3,oneof"`
}

type MessageToClient_CurrentCursorScaleAnswer struct {
	CurrentCursorScaleAnswer *CurrentCursorScaleAnswer `protobuf:"bytes,4,opt,name=current_cursor_scale_answer,json=currentCursorScaleAnswer,proto3,oneof"`
}

func (*MessageToClient_ServerHello) isMessageToClient_Event() {}

func (*MessageToClient_ServerEvent) isMessageToClient_Event() {}

func (*MessageToClient_Pong) isMessageToClient_Event() {}

func (*MessageToClient_CurrentCursorScaleAnswer) isMessageToClient_Event() {}

var File_skymouse_proto protoreflect.FileDescriptor

const file_skymouse_proto_rawDesc = "" +
	"\n" +
	"\x0eskymouse.proto\x12\bskymouse\"\x82\x01\n" +
	"\n" +
	"MouseEvent\x12\x17\n" +
	"\adelta_x\x18\x01 \x01(\x02R\x06deltaX\x12\x17\n" +
	"\adelta_y\x18\x02 \x01(\x02R\x06deltaY\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x1f\n" +
	"\vsequence_id\x18\x04 \x01(\rR\n" +
	"sequenceId\"\x8b\x01\n" +
	"\n" +
	"ClickEvent\x12-\n" +
	"\x06button\x18\x01 \x01(\x0e2\x15.skymouse.MouseButtonR\x06button\x12+\n" +
	"\x05state\x18\x02 \x01(\x0e2\x15.skymouse.ButtonStateR\x05state\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"I\n" +
	"\vScrollEvent\x12\x17\n" +
	"\adelta_y\x18\x01 \x01(\x05R\x06deltaY\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\"L\n" +
	"\x13KeyboardStringEvent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\"\x8b\x01\n" +
	"\x10KeyboardTapEvent\x12'\n" +
	"\x03key\x18\x01 \x01(\x0e2\x15.skymouse.KeyboardKeyR\x03key\x12+\n" +
	"\x05state\x18\x02 \x01(\x0e2\x15.skymouse.ButtonStateR\x05state\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"J\n" +
	"\x04Ping\x12\x1f\n" +
	"\vsequence_id\x18\x01 \x01(\x03R\n" +
	"sequenceId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\"J\n" +
	"\x04Pong\x12\x1f\n" +
	"\vsequence_id\x18\x01 \x01(\x03R\n" +
	"sequenceId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\"4\n" +
	"\vClientHello\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\"l\n" +
	"\vServerHello\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\x12\x19\n" +
	"\budp_port\x18\x02 \x01(\x05R\audpPort\x12\x1b\n" +
	"\tudp_token\x18\x03 \x01(\rR\budpToken\"6\n" +
	"\x13ClipboardShareEvent\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04textB\t\n" +
	"\acontent\"?\n" +
	"\x13SetCursorScaleEvent\x12(\n" +
	"\x10new_cursor_scale\x18\x01 \x01(\x05R\x0enewCursorScale\"\x15\n" +
	"\x13GetCursorScaleEvent\"L\n" +
	"\x18CurrentCursorScaleAnswer\x120\n" +
	"\x14current_cursor_scale\x18\x01 \x01(\x05R\x12currentCursorScale\"_\n" +
	"\vServerEvent\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.skymouse.HapticEventTypeR\x04type\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\"\xc6\x02\n" +
	"\rEmulatorEvent\x12,\n" +
	"\x05mouse\x18\x01 \x01(\v2\x14.skymouse.MouseEventH\x00R\x05mouse\x12,\n" +
	"\x05click\x18\x02 \x01(\v2\x14.skymouse.ClickEventH\x00R\x05click\x12/\n" +
	"\x06scroll\x18\x03 \x01(\v2\x15.skymouse.ScrollEventH\x00R\x06scroll\x12S\n" +
	"\x15keyboard_string_event\x18\x04 \x01(\v2\x1d.skymouse.KeyboardStringEventH\x00R\x13keyboardStringEvent\x12J\n" +
	"\x12keyboard_tap_event\x18\x05 \x01(\v2\x1a.skymouse.KeyboardTapEventH\x00R\x10keyboardTapEventB\a\n" +
	"\x05event\"\xf8\x03\n" +
	"\x0fMessageToServer\x12:\n" +
	"\fclient_hello\x18\x01 \x01(\v2\x15.skymouse.ClientHelloH\x00R\vclientHello\x12@\n" +
	"\x0eemulator_event\x18\x02 \x01(\v2\x17.skymouse.EmulatorEventH\x00R\remulatorEvent\x12$\n" +
	"\x04ping\x18\x03 \x01(\v2\x0e.skymouse.PingH\x00R\x04ping\x12$\n" +
	"\x04pong\x18\x04 \x01(\v2\x0e.skymouse.PongH\x00R\x04pong\x122\n" +
	"\acommand\x18\x05 \x01(\x0e2\x16.skymouse.CommandEventH\x00R\acommand\x12H\n" +
	"\x0fclipboard_share\x18\x06 \x01(\v2\x1d.skymouse.ClipboardShareEventH\x00R\x0eclipboardShare\x12I\n" +
	"\x10get_cursor_scale\x18\a \x01(\v2\x1d.skymouse.GetCursorScaleEventH\x00R\x0egetCursorScale\x12I\n" +
	"\x10set_cursor_scale\x18\b \x01(\v2\x1d.skymouse.SetCursorScaleEventH\x00R\x0esetCursorScaleB\a\n" +
	"\x05event\"\xa2\x01\n" +
	"\x12UdpMessageToServer\x12\x1b\n" +
	"\tudp_token\x18\x01 \x01(\rR\budpToken\x12@\n" +
	"\x0eemulator_event\x18\x02 \x01(\v2\x17.skymouse.EmulatorEventH\x00R\remulatorEvent\x12$\n" +
	"\x04ping\x18\x03 \x01(\v2\x0e.skymouse.PingH\x00R\x04pingB\a\n" +
	"\x05event\"\x9d\x02\n" +
	"\x0fMessageToClient\x12:\n" +
	"\fserver_hello\x18\x01 \x01(\v2\x15.skymouse.ServerHelloH\x00R\vserverHello\x12:\n" +
	"\fserver_event\x18\x02 \x01(\v2\x15.skymouse.ServerEventH\x00R\vserverEvent\x12$\n" +
	"\x04pong\x18\x03 \x01(\v2\x0e.skymouse.PongH\x00R\x04pong\x12c\n" +
	"\x1bcurrent_cursor_scale_answer\x18\x04 \x01(\v2\".skymouse.CurrentCursorScaleAnswerH\x00R\x18currentCursorScaleAnswerB\a\n" +
	"\x05event*W\n" +
	"\vMouseButton\x12\x12\n" +
	"\x0eBUTTON_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vBUTTON_LEFT\x10\x01\x12\x10\n" +
	"\fBUTTON_RIGHT\x10\x02\x12\x11\n" +
	"\rBUTTON_MIDDLE\x10\x03*>\n" +
	"\vButtonState\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"STATE_DOWN\x10\x01\x12\f\n" +
	"\bSTATE_UP\x10\x02*\xb1\x01\n" +
	"\vKeyboardKey\x12\x0f\n" +
	"\vKEY_UNKNOWN\x10\x00\x12\r\n" +
	"\tKEY_ENTER\x10\x01\x12\x11\n" +
	"\rKEY_BACKSPACE\x10\x02\x12\x10\n" +
	"\fKEY_VOL_DOWN\x10\x03\x12\x0e\n" +
	"\n" +
	"KEY_VOL_UP\x10\x04\x12\x10\n" +
	"\fKEY_VOL_MUTE\x10\x05\x12\x13\n" +
	"\x0fKEY_AUDIO_PAUSE\x10\x06\x12\x12\n" +
	"\x0eKEY_AUDIO_PREV\x10\a\x12\x12\n" +
	"\x0eKEY_AUDIO_NEXT\x10\b*S\n" +
	"\x0fHapticEventType\x12\x11\n" +
	"\rEVENT_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15EVENT_BORDER_CROSSING\x10\x01\x12\x12\n" +
	"\x0eEVENT_EDGE_HIT\x10\x02*f\n" +
	"\fCommandEvent\x12\x13\n" +
	"\x0fCOMMAND_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11COMMAND_SHUT_DOWN\x10\x01\x12\x11\n" +
	"\rCOMMAND_SLEEP\x10\x02\x12\x17\n" +
	"\x13COMMAND_LOCK_SCREEN\x10\x03BY\n" +
	"!com.skymouse.skymouseclient.protoP\x01Z2github.com/Tomahawk-Center/SkyMouse/proto;protoapib\x06proto3"

var (
	file_skymouse_proto_rawDescOnce sync.Once
	file_skymouse_proto_rawDescData []byte
)

func file_skymouse_proto_rawDescGZIP() []byte {
	file_skymouse_proto_rawDescOnce.Do(func() {
		file_skymouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skymouse_proto_rawDesc), len(file_skymouse_proto_rawDesc)))
	})
	return file_skymouse_proto_rawDescData
}

var file_skymouse_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_skymouse_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_skymouse_proto_goTypes = []any{
	(MouseButton)(0),                 // 0: skymouse.MouseButton
	(ButtonState)(0),                 // 1: skymouse.ButtonState
	(KeyboardKey)(0),                 // 2: skymouse.KeyboardKey
	(HapticEventType)(0),             // 3: skymouse.HapticEventType
	(CommandEvent)(0),                // 4: skymouse.CommandEvent
	(*MouseEvent)(nil),               // 5: skymouse.MouseEvent
	(*ClickEvent)(nil),               // 6: skymouse.ClickEvent
	(*ScrollEvent)(nil),              // 7: skymouse.ScrollEvent
	(*KeyboardStringEvent)(nil),      // 8: skymouse.KeyboardStringEvent
	(*KeyboardTapEvent)(nil),         // 9: skymouse.KeyboardTapEvent
	(*Ping)(nil),                     // 10: skymouse.Ping
	(*Pong)(nil),                     // 11: skymouse.Pong
	(*ClientHello)(nil),              // 12: skymouse.ClientHello
	(*ServerHello)(nil),              // 13: skymouse.ServerHello
	(*ClipboardShareEvent)(nil),      // 14: skymouse.ClipboardShareEvent
	(*SetCursorScaleEvent)(nil),      // 15: skymouse.SetCursorScaleEvent
	(*GetCursorScaleEvent)(nil),      // 16: skymouse.GetCursorScaleEvent
	(*CurrentCursorScaleAnswer)(nil), // 17: skymouse.CurrentCursorScaleAnswer
	(*ServerEvent)(nil),              // 18: skymouse.ServerEvent
	(*EmulatorEvent)(nil),            // 19: skymouse.EmulatorEvent
	(*MessageToServer)(nil),          // 20: skymouse.MessageToServer
	(*UdpMessageToServer)(nil),       // 21: skymouse.UdpMessageToServer
	(*MessageToClient)(nil),          // 22: skymouse.MessageToClient
}
var file_skymouse_proto_depIdxs = []int32{
	0,  // 0: skymouse.ClickEvent.button:type_name -> skymouse.MouseButton
	1,  // 1: skymouse.ClickEvent.state:type_name -> skymouse.ButtonState
	2,  // 2: skymouse.KeyboardTapEvent.key:type_name -> skymouse.KeyboardKey
	1,  // 3: skymouse.KeyboardTapEvent.state:type_name -> skymouse.ButtonState
	3,  // 4: skymouse.ServerEvent.type:type_name -> skymouse.HapticEventType
	5,  // 5: skymouse.EmulatorEvent.mouse:type_name -> skymouse.MouseEvent
	6,  // 6: skymouse.EmulatorEvent.click:type_name -> skymouse.ClickEvent
	7,  // 7: skymouse.EmulatorEvent.scroll:type_name -> skymouse.ScrollEvent
	8,  // 8: skymouse.EmulatorEvent.keyboard_string_event:type_name -> skymouse.KeyboardStringEvent
	9,  // 9: skymouse.EmulatorEvent.keyboard_tap_event:type_name -> skymouse.KeyboardTapEvent
	12, // 10: skymouse.MessageToServer.client_hello:type_name -> skymouse.ClientHello
	19, // 11: skymouse.MessageToServer.emulator_event:type_name -> skymouse.EmulatorEvent
	10, // 12: skymouse.MessageToServer.ping:type_name -> skymouse.Ping
	11, // 13: skymouse.MessageToServer.pong:type_name -> skymouse.Pong
	4,  // 14: skymouse.MessageToServer.command:type_name -> skymouse.CommandEvent
	14, // 15: skymouse.MessageToServer.clipboard_share:type_name -> skymouse.ClipboardShareEvent
	16, // 16: skymouse.MessageToServer.get_cursor_scale:type_name -> skymouse.GetCursorScaleEvent
	15, // 17: skymouse.MessageToServer.set_cursor_scale:type_name -> skymouse.SetCursorScaleEvent
	19, // 18: skymouse.UdpMessageToServer.emulator_event:type_name -> skymouse.EmulatorEvent
	10, // 19: skymouse.UdpMessageToServer.ping:type_name -> skymouse.Ping
	13, // 20: skymouse.MessageToClient.server_hello:type_name -> skymouse.ServerHello
	18, // 21: skymouse.MessageToClient.server_event:type_name -> skymouse.ServerEvent
	11, // 22: skymouse.MessageToClient.pong:type_name -> skymouse.Pong
	17, // 23: skymouse.MessageToClient.current_cursor_scale_answer:type_name -> skymouse.CurrentCursorScaleAnswer
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_skymouse_proto_init() }
func file_skymouse_proto_init() {
	if File_skymouse_proto != nil {
		return
	}
	file_skymouse_proto_msgTypes[9].OneofWrappers = []any{
		(*ClipboardShareEvent_Text)(nil),
	}
	file_skymouse_proto_msgTypes[14].OneofWrappers = []any{
		(*EmulatorEvent_Mouse)(nil),
		(*EmulatorEvent_Click)(nil),
		(*EmulatorEvent_Scroll)(nil),
		(*EmulatorEvent_KeyboardStringEvent)(nil),
		(*EmulatorEvent_KeyboardTapEvent)(nil),
	}
	file_skymouse_proto_msgTypes[15].OneofWrappers = []any{
		(*MessageToServer_ClientHello)(nil),
		(*MessageToServer_EmulatorEvent)(nil),
		(*MessageToServer_Ping)(nil),
		(*MessageToServer_Pong)(nil),
		(*MessageToServer_Command)(nil),
		(*MessageToServer_ClipboardShare)(nil),
		(*MessageToServer_GetCursorScale)(nil),
		(*MessageToServer_SetCursorScale)(nil),
	}
	file_skymouse_proto_msgTypes[16].OneofWrappers = []any{
		(*UdpMessageToServer_EmulatorEvent)(nil),
		(*UdpMessageToServer_Ping)(nil),
	}
	file_skymouse_proto_msgTypes[17].OneofWrappers = []any{
		(*MessageToClient_ServerHello)(nil),
		(*MessageToClient_ServerEvent)(nil),
		(*MessageToClient_Pong)(nil),
		(*MessageToClient_CurrentCursorScaleAnswer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skymouse_proto_rawDesc), len(file_skymouse_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skymouse_proto_goTypes,
		DependencyIndexes: file_skymouse_proto_depIdxs,
		EnumInfos:         file_skymouse_proto_enumTypes,
		MessageInfos:      file_skymouse_proto_msgTypes,
	}.Build()
	File_skymouse_proto = out.File
	file_skymouse_proto_goTypes = nil
	file_skymouse_proto_depIdxs = nil
}
